/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vnpt.portlet.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ActIdInfo service. Represents a row in the &quot;act_id_info&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vnpt.portlet.user.model.impl.ActIdInfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vnpt.portlet.user.model.impl.ActIdInfoImpl}.
 * </p>
 *
 * @author ToanNQ86
 * @see ActIdInfo
 * @see com.vnpt.portlet.user.model.impl.ActIdInfoImpl
 * @see com.vnpt.portlet.user.model.impl.ActIdInfoModelImpl
 * @generated
 */
public interface ActIdInfoModel extends BaseModel<ActIdInfo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a act ID info model instance should use the {@link ActIdInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this act ID info.
	 *
	 * @return the primary key of this act ID info
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this act ID info.
	 *
	 * @param primaryKey the primary key of this act ID info
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this act ID info.
	 *
	 * @return the ID of this act ID info
	 */
	public long getId();

	/**
	 * Sets the ID of this act ID info.
	 *
	 * @param id the ID of this act ID info
	 */
	public void setId(long id);

	/**
	 * Returns the rev of this act ID info.
	 *
	 * @return the rev of this act ID info
	 */
	public long getRev();

	/**
	 * Sets the rev of this act ID info.
	 *
	 * @param rev the rev of this act ID info
	 */
	public void setRev(long rev);

	/**
	 * Returns the user ID of this act ID info.
	 *
	 * @return the user ID of this act ID info
	 */
	@AutoEscape
	public String getUserId();

	/**
	 * Sets the user ID of this act ID info.
	 *
	 * @param userId the user ID of this act ID info
	 */
	public void setUserId(String userId);

	/**
	 * Returns the type of this act ID info.
	 *
	 * @return the type of this act ID info
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this act ID info.
	 *
	 * @param type the type of this act ID info
	 */
	public void setType(String type);

	/**
	 * Returns the key of this act ID info.
	 *
	 * @return the key of this act ID info
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this act ID info.
	 *
	 * @param key the key of this act ID info
	 */
	public void setKey(String key);

	/**
	 * Returns the value of this act ID info.
	 *
	 * @return the value of this act ID info
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this act ID info.
	 *
	 * @param value the value of this act ID info
	 */
	public void setValue(String value);

	/**
	 * Returns the password of this act ID info.
	 *
	 * @return the password of this act ID info
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this act ID info.
	 *
	 * @param password the password of this act ID info
	 */
	public void setPassword(String password);

	/**
	 * Returns the parent_id_ of this act ID info.
	 *
	 * @return the parent_id_ of this act ID info
	 */
	@AutoEscape
	public String getParent_id_();

	/**
	 * Sets the parent_id_ of this act ID info.
	 *
	 * @param parent_id_ the parent_id_ of this act ID info
	 */
	public void setParent_id_(String parent_id_);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.vnpt.portlet.user.model.ActIdInfo actIdInfo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.vnpt.portlet.user.model.ActIdInfo> toCacheModel();

	@Override
	public com.vnpt.portlet.user.model.ActIdInfo toEscapedModel();

	@Override
	public com.vnpt.portlet.user.model.ActIdInfo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}