/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vnpt.portlet.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ActIdUser service. Represents a row in the &quot;act_id_user&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vnpt.portlet.user.model.impl.ActIdUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vnpt.portlet.user.model.impl.ActIdUserImpl}.
 * </p>
 *
 * @author ToanNQ86
 * @see ActIdUser
 * @see com.vnpt.portlet.user.model.impl.ActIdUserImpl
 * @see com.vnpt.portlet.user.model.impl.ActIdUserModelImpl
 * @generated
 */
public interface ActIdUserModel extends BaseModel<ActIdUser> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a act ID user model instance should use the {@link ActIdUser} interface instead.
	 */

	/**
	 * Returns the primary key of this act ID user.
	 *
	 * @return the primary key of this act ID user
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this act ID user.
	 *
	 * @param primaryKey the primary key of this act ID user
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the ID of this act ID user.
	 *
	 * @return the ID of this act ID user
	 */
	@AutoEscape
	public String getId();

	/**
	 * Sets the ID of this act ID user.
	 *
	 * @param id the ID of this act ID user
	 */
	public void setId(String id);

	/**
	 * Returns the rev of this act ID user.
	 *
	 * @return the rev of this act ID user
	 */
	public long getRev();

	/**
	 * Sets the rev of this act ID user.
	 *
	 * @param rev the rev of this act ID user
	 */
	public void setRev(long rev);

	/**
	 * Returns the first of this act ID user.
	 *
	 * @return the first of this act ID user
	 */
	@AutoEscape
	public String getFirst();

	/**
	 * Sets the first of this act ID user.
	 *
	 * @param first the first of this act ID user
	 */
	public void setFirst(String first);

	/**
	 * Returns the last of this act ID user.
	 *
	 * @return the last of this act ID user
	 */
	@AutoEscape
	public String getLast();

	/**
	 * Sets the last of this act ID user.
	 *
	 * @param last the last of this act ID user
	 */
	public void setLast(String last);

	/**
	 * Returns the email of this act ID user.
	 *
	 * @return the email of this act ID user
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this act ID user.
	 *
	 * @param email the email of this act ID user
	 */
	public void setEmail(String email);

	/**
	 * Returns the pwd of this act ID user.
	 *
	 * @return the pwd of this act ID user
	 */
	@AutoEscape
	public String getPwd();

	/**
	 * Sets the pwd of this act ID user.
	 *
	 * @param pwd the pwd of this act ID user
	 */
	public void setPwd(String pwd);

	/**
	 * Returns the picture ID of this act ID user.
	 *
	 * @return the picture ID of this act ID user
	 */
	@AutoEscape
	public String getPictureId();

	/**
	 * Sets the picture ID of this act ID user.
	 *
	 * @param pictureId the picture ID of this act ID user
	 */
	public void setPictureId(String pictureId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.vnpt.portlet.user.model.ActIdUser actIdUser);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.vnpt.portlet.user.model.ActIdUser> toCacheModel();

	@Override
	public com.vnpt.portlet.user.model.ActIdUser toEscapedModel();

	@Override
	public com.vnpt.portlet.user.model.ActIdUser toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}