/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vnpt.portlet.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LiferayDatabase service. Represents a row in the &quot;shoppingitemfield&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vnpt.portlet.user.model.impl.LiferayDatabaseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vnpt.portlet.user.model.impl.LiferayDatabaseImpl}.
 * </p>
 *
 * @author ToanNQ86
 * @see LiferayDatabase
 * @see com.vnpt.portlet.user.model.impl.LiferayDatabaseImpl
 * @see com.vnpt.portlet.user.model.impl.LiferayDatabaseModelImpl
 * @generated
 */
public interface LiferayDatabaseModel extends BaseModel<LiferayDatabase> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a liferay database model instance should use the {@link LiferayDatabase} interface instead.
	 */

	/**
	 * Returns the primary key of this liferay database.
	 *
	 * @return the primary key of this liferay database
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this liferay database.
	 *
	 * @param primaryKey the primary key of this liferay database
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the item field ID of this liferay database.
	 *
	 * @return the item field ID of this liferay database
	 */
	public long getItemFieldId();

	/**
	 * Sets the item field ID of this liferay database.
	 *
	 * @param itemFieldId the item field ID of this liferay database
	 */
	public void setItemFieldId(long itemFieldId);

	/**
	 * Returns the item ID of this liferay database.
	 *
	 * @return the item ID of this liferay database
	 */
	public long getItemId();

	/**
	 * Sets the item ID of this liferay database.
	 *
	 * @param itemId the item ID of this liferay database
	 */
	public void setItemId(long itemId);

	/**
	 * Returns the name of this liferay database.
	 *
	 * @return the name of this liferay database
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this liferay database.
	 *
	 * @param name the name of this liferay database
	 */
	public void setName(String name);

	/**
	 * Returns the values of this liferay database.
	 *
	 * @return the values of this liferay database
	 */
	@AutoEscape
	public String getValues();

	/**
	 * Sets the values of this liferay database.
	 *
	 * @param values the values of this liferay database
	 */
	public void setValues(String values);

	/**
	 * Returns the description of this liferay database.
	 *
	 * @return the description of this liferay database
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this liferay database.
	 *
	 * @param description the description of this liferay database
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.vnpt.portlet.user.model.LiferayDatabase liferayDatabase);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.vnpt.portlet.user.model.LiferayDatabase> toCacheModel();

	@Override
	public com.vnpt.portlet.user.model.LiferayDatabase toEscapedModel();

	@Override
	public com.vnpt.portlet.user.model.LiferayDatabase toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}