/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vnpt.portlet.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PermissionGroup service. Represents a row in the &quot;eportal_permission_group&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vnpt.portlet.user.model.impl.PermissionGroupModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vnpt.portlet.user.model.impl.PermissionGroupImpl}.
 * </p>
 *
 * @author ToanNQ86
 * @see PermissionGroup
 * @see com.vnpt.portlet.user.model.impl.PermissionGroupImpl
 * @see com.vnpt.portlet.user.model.impl.PermissionGroupModelImpl
 * @generated
 */
public interface PermissionGroupModel extends BaseModel<PermissionGroup> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a permission group model instance should use the {@link PermissionGroup} interface instead.
	 */

	/**
	 * Returns the primary key of this permission group.
	 *
	 * @return the primary key of this permission group
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this permission group.
	 *
	 * @param primaryKey the primary key of this permission group
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the permission group ID of this permission group.
	 *
	 * @return the permission group ID of this permission group
	 */
	public long getPermissionGroupId();

	/**
	 * Sets the permission group ID of this permission group.
	 *
	 * @param permissionGroupId the permission group ID of this permission group
	 */
	public void setPermissionGroupId(long permissionGroupId);

	/**
	 * Returns the group ID of this permission group.
	 *
	 * @return the group ID of this permission group
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this permission group.
	 *
	 * @param groupId the group ID of this permission group
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this permission group.
	 *
	 * @return the company ID of this permission group
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this permission group.
	 *
	 * @param companyId the company ID of this permission group
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group name of this permission group.
	 *
	 * @return the group name of this permission group
	 */
	@AutoEscape
	public String getGroupName();

	/**
	 * Sets the group name of this permission group.
	 *
	 * @param groupName the group name of this permission group
	 */
	public void setGroupName(String groupName);

	/**
	 * Returns the group code of this permission group.
	 *
	 * @return the group code of this permission group
	 */
	@AutoEscape
	public String getGroupCode();

	/**
	 * Sets the group code of this permission group.
	 *
	 * @param groupCode the group code of this permission group
	 */
	public void setGroupCode(String groupCode);

	/**
	 * Returns the is active of this permission group.
	 *
	 * @return the is active of this permission group
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this permission group.
	 *
	 * @param isActive the is active of this permission group
	 */
	public void setIsActive(int isActive);

	/**
	 * Returns the description of this permission group.
	 *
	 * @return the description of this permission group
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this permission group.
	 *
	 * @param description the description of this permission group
	 */
	public void setDescription(String description);

	/**
	 * Returns the role ID of this permission group.
	 *
	 * @return the role ID of this permission group
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this permission group.
	 *
	 * @param roleId the role ID of this permission group
	 */
	public void setRoleId(long roleId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.vnpt.portlet.user.model.PermissionGroup permissionGroup);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.vnpt.portlet.user.model.PermissionGroup> toCacheModel();

	@Override
	public com.vnpt.portlet.user.model.PermissionGroup toEscapedModel();

	@Override
	public com.vnpt.portlet.user.model.PermissionGroup toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}