/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vnpt.portlet.user.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.vnpt.portlet.user.model.LiferayDatabase;
import com.vnpt.portlet.user.model.LiferayDatabaseModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LiferayDatabase service. Represents a row in the &quot;shoppingitemfield&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vnpt.portlet.user.model.LiferayDatabaseModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LiferayDatabaseImpl}.
 * </p>
 *
 * @author ToanNQ86
 * @see LiferayDatabaseImpl
 * @see com.vnpt.portlet.user.model.LiferayDatabase
 * @see com.vnpt.portlet.user.model.LiferayDatabaseModel
 * @generated
 */
public class LiferayDatabaseModelImpl extends BaseModelImpl<LiferayDatabase>
	implements LiferayDatabaseModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a liferay database model instance should use the {@link com.vnpt.portlet.user.model.LiferayDatabase} interface instead.
	 */
	public static final String TABLE_NAME = "shoppingitemfield";
	public static final Object[][] TABLE_COLUMNS = {
			{ "itemFieldId", Types.BIGINT },
			{ "itemId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "values_", Types.VARCHAR },
			{ "description", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table shoppingitemfield (itemFieldId LONG not null primary key,itemId LONG,name VARCHAR(75) null,values_ VARCHAR(75) null,description VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table shoppingitemfield";
	public static final String ORDER_BY_JPQL = " ORDER BY liferayDatabase.itemFieldId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY shoppingitemfield.itemFieldId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vnpt.portlet.user.model.LiferayDatabase"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vnpt.portlet.user.model.LiferayDatabase"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.vnpt.portlet.user.model.LiferayDatabase"),
			true);
	public static long ITEMID_COLUMN_BITMASK = 1L;
	public static long ITEMFIELDID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vnpt.portlet.user.model.LiferayDatabase"));

	public LiferayDatabaseModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _itemFieldId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setItemFieldId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _itemFieldId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LiferayDatabase.class;
	}

	@Override
	public String getModelClassName() {
		return LiferayDatabase.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("itemFieldId", getItemFieldId());
		attributes.put("itemId", getItemId());
		attributes.put("name", getName());
		attributes.put("values", getValues());
		attributes.put("description", getDescription());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long itemFieldId = (Long)attributes.get("itemFieldId");

		if (itemFieldId != null) {
			setItemFieldId(itemFieldId);
		}

		Long itemId = (Long)attributes.get("itemId");

		if (itemId != null) {
			setItemId(itemId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String values = (String)attributes.get("values");

		if (values != null) {
			setValues(values);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}
	}

	@Override
	public long getItemFieldId() {
		return _itemFieldId;
	}

	@Override
	public void setItemFieldId(long itemFieldId) {
		_itemFieldId = itemFieldId;
	}

	@Override
	public long getItemId() {
		return _itemId;
	}

	@Override
	public void setItemId(long itemId) {
		_columnBitmask |= ITEMID_COLUMN_BITMASK;

		if (!_setOriginalItemId) {
			_setOriginalItemId = true;

			_originalItemId = _itemId;
		}

		_itemId = itemId;
	}

	public long getOriginalItemId() {
		return _originalItemId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getValues() {
		if (_values == null) {
			return StringPool.BLANK;
		}
		else {
			return _values;
		}
	}

	@Override
	public void setValues(String values) {
		_values = values;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			LiferayDatabase.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LiferayDatabase toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LiferayDatabase)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LiferayDatabaseImpl liferayDatabaseImpl = new LiferayDatabaseImpl();

		liferayDatabaseImpl.setItemFieldId(getItemFieldId());
		liferayDatabaseImpl.setItemId(getItemId());
		liferayDatabaseImpl.setName(getName());
		liferayDatabaseImpl.setValues(getValues());
		liferayDatabaseImpl.setDescription(getDescription());

		liferayDatabaseImpl.resetOriginalValues();

		return liferayDatabaseImpl;
	}

	@Override
	public int compareTo(LiferayDatabase liferayDatabase) {
		long primaryKey = liferayDatabase.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LiferayDatabase)) {
			return false;
		}

		LiferayDatabase liferayDatabase = (LiferayDatabase)obj;

		long primaryKey = liferayDatabase.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		LiferayDatabaseModelImpl liferayDatabaseModelImpl = this;

		liferayDatabaseModelImpl._originalItemId = liferayDatabaseModelImpl._itemId;

		liferayDatabaseModelImpl._setOriginalItemId = false;

		liferayDatabaseModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LiferayDatabase> toCacheModel() {
		LiferayDatabaseCacheModel liferayDatabaseCacheModel = new LiferayDatabaseCacheModel();

		liferayDatabaseCacheModel.itemFieldId = getItemFieldId();

		liferayDatabaseCacheModel.itemId = getItemId();

		liferayDatabaseCacheModel.name = getName();

		String name = liferayDatabaseCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			liferayDatabaseCacheModel.name = null;
		}

		liferayDatabaseCacheModel.values = getValues();

		String values = liferayDatabaseCacheModel.values;

		if ((values != null) && (values.length() == 0)) {
			liferayDatabaseCacheModel.values = null;
		}

		liferayDatabaseCacheModel.description = getDescription();

		String description = liferayDatabaseCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			liferayDatabaseCacheModel.description = null;
		}

		return liferayDatabaseCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{itemFieldId=");
		sb.append(getItemFieldId());
		sb.append(", itemId=");
		sb.append(getItemId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", values=");
		sb.append(getValues());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.vnpt.portlet.user.model.LiferayDatabase");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>itemFieldId</column-name><column-value><![CDATA[");
		sb.append(getItemFieldId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>itemId</column-name><column-value><![CDATA[");
		sb.append(getItemId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>values</column-name><column-value><![CDATA[");
		sb.append(getValues());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = LiferayDatabase.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			LiferayDatabase.class
		};
	private long _itemFieldId;
	private long _itemId;
	private long _originalItemId;
	private boolean _setOriginalItemId;
	private String _name;
	private String _values;
	private String _description;
	private long _columnBitmask;
	private LiferayDatabase _escapedModel;
}