/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vnpt.portlet.user.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.vnpt.portlet.user.model.PermissionGroup;
import com.vnpt.portlet.user.model.PermissionGroupModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PermissionGroup service. Represents a row in the &quot;eportal_permission_group&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vnpt.portlet.user.model.PermissionGroupModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PermissionGroupImpl}.
 * </p>
 *
 * @author ToanNQ86
 * @see PermissionGroupImpl
 * @see com.vnpt.portlet.user.model.PermissionGroup
 * @see com.vnpt.portlet.user.model.PermissionGroupModel
 * @generated
 */
public class PermissionGroupModelImpl extends BaseModelImpl<PermissionGroup>
	implements PermissionGroupModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a permission group model instance should use the {@link com.vnpt.portlet.user.model.PermissionGroup} interface instead.
	 */
	public static final String TABLE_NAME = "eportal_permission_group";
	public static final Object[][] TABLE_COLUMNS = {
			{ "permissionGroupId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupName", Types.VARCHAR },
			{ "groupCode", Types.VARCHAR },
			{ "isActive", Types.INTEGER },
			{ "description", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table eportal_permission_group (permissionGroupId LONG not null primary key,groupId LONG,companyId LONG,groupName VARCHAR(75) null,groupCode VARCHAR(75) null,isActive INTEGER,description VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table eportal_permission_group";
	public static final String ORDER_BY_JPQL = " ORDER BY permissionGroup.permissionGroupId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eportal_permission_group.permissionGroupId ASC";
	public static final String DATA_SOURCE = "eGovDataSource";
	public static final String SESSION_FACTORY = "eGovSessionFactory";
	public static final String TX_MANAGER = "eGovTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vnpt.portlet.user.model.PermissionGroup"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vnpt.portlet.user.model.PermissionGroup"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.vnpt.portlet.user.model.PermissionGroup"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long ISACTIVE_COLUMN_BITMASK = 4L;
	public static long PERMISSIONGROUPID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vnpt.portlet.user.model.PermissionGroup"));

	public PermissionGroupModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _permissionGroupId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPermissionGroupId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _permissionGroupId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PermissionGroup.class;
	}

	@Override
	public String getModelClassName() {
		return PermissionGroup.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("permissionGroupId", getPermissionGroupId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupName", getGroupName());
		attributes.put("groupCode", getGroupCode());
		attributes.put("isActive", getIsActive());
		attributes.put("description", getDescription());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long permissionGroupId = (Long)attributes.get("permissionGroupId");

		if (permissionGroupId != null) {
			setPermissionGroupId(permissionGroupId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		String groupName = (String)attributes.get("groupName");

		if (groupName != null) {
			setGroupName(groupName);
		}

		String groupCode = (String)attributes.get("groupCode");

		if (groupCode != null) {
			setGroupCode(groupCode);
		}

		Integer isActive = (Integer)attributes.get("isActive");

		if (isActive != null) {
			setIsActive(isActive);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}
	}

	@Override
	public long getPermissionGroupId() {
		return _permissionGroupId;
	}

	@Override
	public void setPermissionGroupId(long permissionGroupId) {
		_permissionGroupId = permissionGroupId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public String getGroupName() {
		if (_groupName == null) {
			return StringPool.BLANK;
		}
		else {
			return _groupName;
		}
	}

	@Override
	public void setGroupName(String groupName) {
		_groupName = groupName;
	}

	@Override
	public String getGroupCode() {
		if (_groupCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _groupCode;
		}
	}

	@Override
	public void setGroupCode(String groupCode) {
		_groupCode = groupCode;
	}

	@Override
	public int getIsActive() {
		return _isActive;
	}

	@Override
	public void setIsActive(int isActive) {
		_columnBitmask |= ISACTIVE_COLUMN_BITMASK;

		if (!_setOriginalIsActive) {
			_setOriginalIsActive = true;

			_originalIsActive = _isActive;
		}

		_isActive = isActive;
	}

	public int getOriginalIsActive() {
		return _originalIsActive;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			PermissionGroup.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PermissionGroup toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PermissionGroup)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PermissionGroupImpl permissionGroupImpl = new PermissionGroupImpl();

		permissionGroupImpl.setPermissionGroupId(getPermissionGroupId());
		permissionGroupImpl.setGroupId(getGroupId());
		permissionGroupImpl.setCompanyId(getCompanyId());
		permissionGroupImpl.setGroupName(getGroupName());
		permissionGroupImpl.setGroupCode(getGroupCode());
		permissionGroupImpl.setIsActive(getIsActive());
		permissionGroupImpl.setDescription(getDescription());

		permissionGroupImpl.resetOriginalValues();

		return permissionGroupImpl;
	}

	@Override
	public int compareTo(PermissionGroup permissionGroup) {
		long primaryKey = permissionGroup.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PermissionGroup)) {
			return false;
		}

		PermissionGroup permissionGroup = (PermissionGroup)obj;

		long primaryKey = permissionGroup.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		PermissionGroupModelImpl permissionGroupModelImpl = this;

		permissionGroupModelImpl._originalGroupId = permissionGroupModelImpl._groupId;

		permissionGroupModelImpl._setOriginalGroupId = false;

		permissionGroupModelImpl._originalCompanyId = permissionGroupModelImpl._companyId;

		permissionGroupModelImpl._setOriginalCompanyId = false;

		permissionGroupModelImpl._originalIsActive = permissionGroupModelImpl._isActive;

		permissionGroupModelImpl._setOriginalIsActive = false;

		permissionGroupModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PermissionGroup> toCacheModel() {
		PermissionGroupCacheModel permissionGroupCacheModel = new PermissionGroupCacheModel();

		permissionGroupCacheModel.permissionGroupId = getPermissionGroupId();

		permissionGroupCacheModel.groupId = getGroupId();

		permissionGroupCacheModel.companyId = getCompanyId();

		permissionGroupCacheModel.groupName = getGroupName();

		String groupName = permissionGroupCacheModel.groupName;

		if ((groupName != null) && (groupName.length() == 0)) {
			permissionGroupCacheModel.groupName = null;
		}

		permissionGroupCacheModel.groupCode = getGroupCode();

		String groupCode = permissionGroupCacheModel.groupCode;

		if ((groupCode != null) && (groupCode.length() == 0)) {
			permissionGroupCacheModel.groupCode = null;
		}

		permissionGroupCacheModel.isActive = getIsActive();

		permissionGroupCacheModel.description = getDescription();

		String description = permissionGroupCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			permissionGroupCacheModel.description = null;
		}

		return permissionGroupCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{permissionGroupId=");
		sb.append(getPermissionGroupId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupName=");
		sb.append(getGroupName());
		sb.append(", groupCode=");
		sb.append(getGroupCode());
		sb.append(", isActive=");
		sb.append(getIsActive());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.vnpt.portlet.user.model.PermissionGroup");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>permissionGroupId</column-name><column-value><![CDATA[");
		sb.append(getPermissionGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupName</column-name><column-value><![CDATA[");
		sb.append(getGroupName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupCode</column-name><column-value><![CDATA[");
		sb.append(getGroupCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isActive</column-name><column-value><![CDATA[");
		sb.append(getIsActive());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PermissionGroup.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PermissionGroup.class
		};
	private long _permissionGroupId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private String _groupName;
	private String _groupCode;
	private int _isActive;
	private int _originalIsActive;
	private boolean _setOriginalIsActive;
	private String _description;
	private long _columnBitmask;
	private PermissionGroup _escapedModel;
}