/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.viettel.ims.core.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.viettel.ims.core.model.InvestPolicyExt;
import com.viettel.ims.core.model.InvestPolicyExtModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the InvestPolicyExt service. Represents a row in the &quot;VTIMS_InvestPolicyExt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.viettel.ims.core.model.InvestPolicyExtModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InvestPolicyExtImpl}.
 * </p>
 *
 * @author MrNet
 * @see InvestPolicyExtImpl
 * @see com.viettel.ims.core.model.InvestPolicyExt
 * @see com.viettel.ims.core.model.InvestPolicyExtModel
 * @generated
 */
public class InvestPolicyExtModelImpl extends BaseModelImpl<InvestPolicyExt>
	implements InvestPolicyExtModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a invest policy ext model instance should use the {@link com.viettel.ims.core.model.InvestPolicyExt} interface instead.
	 */
	public static final String TABLE_NAME = "VTIMS_InvestPolicyExt";
	public static final Object[][] TABLE_COLUMNS = {
			{ "invest_policy_id", Types.BIGINT },
			{ "info_policy_type", Types.BIGINT },
			{ "info_policy_name", Types.VARCHAR },
			{ "info_policy_code", Types.VARCHAR },
			{ "info_propose_group_id", Types.BIGINT },
			{ "info_verify_group_id", Types.BIGINT },
			{ "info_policy_date", Types.TIMESTAMP },
			{ "info_Policy_Deploy_Date", Types.TIMESTAMP },
			{ "info_Responsible_User_Id", Types.BIGINT },
			{ "info_Service", Types.VARCHAR },
			{ "info_Invest_Target", Types.VARCHAR },
			{ "info_Invest_Location", Types.VARCHAR },
			{ "info_Technique", Types.VARCHAR },
			{ "info_invest_name", Types.VARCHAR },
			{ "info_invest_deadline", Types.BIGINT },
			{ "info_Invest_Create_Group_Id", Types.BIGINT },
			{ "info_Invest_Deploy_Group_Id", Types.BIGINT },
			{ "cost_Capital", Types.BIGINT },
			{ "cost_Compensate", Types.DOUBLE },
			{ "cost_Compensate_Foreign", Types.DOUBLE },
			{ "cost_Equiment", Types.DOUBLE },
			{ "cost_Equiment_Foreign", Types.DOUBLE },
			{ "cost_Contruction", Types.DOUBLE },
			{ "cost_Contruction_Foreign", Types.DOUBLE },
			{ "cost_Advisory", Types.DOUBLE },
			{ "cost_Advisory_Foreign", Types.DOUBLE },
			{ "cost_Manager", Types.DOUBLE },
			{ "cost_Manager_Foreign", Types.DOUBLE },
			{ "cost_Other", Types.DOUBLE },
			{ "cost_Other_Foreign", Types.DOUBLE },
			{ "cost_Provide", Types.DOUBLE },
			{ "cost_Provide_Foreign", Types.DOUBLE },
			{ "cost_Local", Types.DOUBLE },
			{ "cost_Foreign", Types.DOUBLE },
			{ "cost_Foreign_Rate", Types.DOUBLE },
			{ "cost_Tax", Types.DOUBLE },
			{ "cost_Total_Value", Types.DOUBLE },
			{ "cost_Total_Value_Tax", Types.DOUBLE },
			{ "decide_Deliverer_User_Id", Types.BIGINT },
			{ "decide_Receive_User_Id", Types.BIGINT },
			{ "decide_Ask_Date", Types.TIMESTAMP },
			{ "decide_Deadline", Types.BIGINT },
			{ "decide_Finish_Date", Types.TIMESTAMP },
			{ "decide_Description", Types.VARCHAR },
			{ "decide_User_Id", Types.BIGINT },
			{ "decide_Date", Types.TIMESTAMP },
			{ "verify_Status", Types.BIGINT },
			{ "verify_Doc_Num", Types.VARCHAR },
			{ "verify_Date", Types.TIMESTAMP },
			{ "verify_User_Id", Types.BIGINT },
			{ "verify_Description", Types.VARCHAR },
			{ "is_Active", Types.BIGINT },
			{ "status", Types.BIGINT },
			{ "created_id", Types.BIGINT },
			{ "created_Date", Types.TIMESTAMP },
			{ "modifield_Id", Types.BIGINT },
			{ "modifield_Date", Types.TIMESTAMP },
			{ "infoPolicyTypeName", Types.VARCHAR },
			{ "infoProposeGroupName", Types.VARCHAR },
			{ "infoVerifyGroupName", Types.VARCHAR },
			{ "infoResponsibleUserName", Types.VARCHAR },
			{ "infoInvestCreateGroupName", Types.VARCHAR },
			{ "infoInvestDeployGroupName", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table VTIMS_InvestPolicyExt (invest_policy_id LONG not null primary key,info_policy_type LONG,info_policy_name VARCHAR(75) null,info_policy_code VARCHAR(75) null,info_propose_group_id LONG,info_verify_group_id LONG,info_policy_date DATE null,info_Policy_Deploy_Date DATE null,info_Responsible_User_Id LONG,info_Service VARCHAR(75) null,info_Invest_Target VARCHAR(75) null,info_Invest_Location VARCHAR(75) null,info_Technique VARCHAR(75) null,info_invest_name VARCHAR(75) null,info_invest_deadline LONG,info_Invest_Create_Group_Id LONG,info_Invest_Deploy_Group_Id LONG,cost_Capital LONG,cost_Compensate DOUBLE,cost_Compensate_Foreign DOUBLE,cost_Equiment DOUBLE,cost_Equiment_Foreign DOUBLE,cost_Contruction DOUBLE,cost_Contruction_Foreign DOUBLE,cost_Advisory DOUBLE,cost_Advisory_Foreign DOUBLE,cost_Manager DOUBLE,cost_Manager_Foreign DOUBLE,cost_Other DOUBLE,cost_Other_Foreign DOUBLE,cost_Provide DOUBLE,cost_Provide_Foreign DOUBLE,cost_Local DOUBLE,cost_Foreign DOUBLE,cost_Foreign_Rate DOUBLE,cost_Tax DOUBLE,cost_Total_Value DOUBLE,cost_Total_Value_Tax DOUBLE,decide_Deliverer_User_Id LONG,decide_Receive_User_Id LONG,decide_Ask_Date DATE null,decide_Deadline LONG,decide_Finish_Date DATE null,decide_Description VARCHAR(75) null,decide_User_Id LONG,decide_Date DATE null,verify_Status LONG,verify_Doc_Num VARCHAR(75) null,verify_Date DATE null,verify_User_Id LONG,verify_Description VARCHAR(75) null,is_Active LONG,status LONG,created_id LONG,created_Date DATE null,modifield_Id LONG,modifield_Date DATE null,infoPolicyTypeName VARCHAR(75) null,infoProposeGroupName VARCHAR(75) null,infoVerifyGroupName VARCHAR(75) null,infoResponsibleUserName VARCHAR(75) null,infoInvestCreateGroupName VARCHAR(75) null,infoInvestDeployGroupName VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table VTIMS_InvestPolicyExt";
	public static final String ORDER_BY_JPQL = " ORDER BY investPolicyExt.createdDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VTIMS_InvestPolicyExt.created_Date DESC";
	public static final String DATA_SOURCE = "noDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.viettel.ims.core.model.InvestPolicyExt"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.viettel.ims.core.model.InvestPolicyExt"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.viettel.ims.core.model.InvestPolicyExt"),
			true);
	public static long INFOPOLICYNAME_COLUMN_BITMASK = 1L;
	public static long ISACTIVE_COLUMN_BITMASK = 2L;
	public static long CREATEDDATE_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.viettel.ims.core.model.InvestPolicyExt"));

	public InvestPolicyExtModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _investPolicyId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setInvestPolicyId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _investPolicyId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return InvestPolicyExt.class;
	}

	@Override
	public String getModelClassName() {
		return InvestPolicyExt.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("investPolicyId", getInvestPolicyId());
		attributes.put("infoPolicyType", getInfoPolicyType());
		attributes.put("infoPolicyName", getInfoPolicyName());
		attributes.put("infoPolicyCode", getInfoPolicyCode());
		attributes.put("infoProposeGroupId", getInfoProposeGroupId());
		attributes.put("infoVerifyGroupId", getInfoVerifyGroupId());
		attributes.put("infoPolicyDate", getInfoPolicyDate());
		attributes.put("infoPolicyDeployDate", getInfoPolicyDeployDate());
		attributes.put("infoResponsibleUserId", getInfoResponsibleUserId());
		attributes.put("infoService", getInfoService());
		attributes.put("infoInvestTarget", getInfoInvestTarget());
		attributes.put("infoInvestLocation", getInfoInvestLocation());
		attributes.put("infoTechnique", getInfoTechnique());
		attributes.put("infoInvestName", getInfoInvestName());
		attributes.put("infoInvestDeadline", getInfoInvestDeadline());
		attributes.put("infoInvestCreateGroupId", getInfoInvestCreateGroupId());
		attributes.put("infoInvestDeployGroupId", getInfoInvestDeployGroupId());
		attributes.put("costCapital", getCostCapital());
		attributes.put("costCompensate", getCostCompensate());
		attributes.put("costCompensateForeign", getCostCompensateForeign());
		attributes.put("costEquiment", getCostEquiment());
		attributes.put("costEquimentForeign", getCostEquimentForeign());
		attributes.put("costContruction", getCostContruction());
		attributes.put("costContructionForeign", getCostContructionForeign());
		attributes.put("costAdvisory", getCostAdvisory());
		attributes.put("costAdvisoryForeign", getCostAdvisoryForeign());
		attributes.put("costManager", getCostManager());
		attributes.put("costManagerForeign", getCostManagerForeign());
		attributes.put("costOther", getCostOther());
		attributes.put("costOtherForeign", getCostOtherForeign());
		attributes.put("costProvide", getCostProvide());
		attributes.put("costProvideForeign", getCostProvideForeign());
		attributes.put("costLocal", getCostLocal());
		attributes.put("costForeign", getCostForeign());
		attributes.put("costForeignRate", getCostForeignRate());
		attributes.put("costTax", getCostTax());
		attributes.put("costTotalValue", getCostTotalValue());
		attributes.put("costTotalValueTax", getCostTotalValueTax());
		attributes.put("decideDelivererUserId", getDecideDelivererUserId());
		attributes.put("decideReceiveUserId", getDecideReceiveUserId());
		attributes.put("decideAskDate", getDecideAskDate());
		attributes.put("decideDeadline", getDecideDeadline());
		attributes.put("decideFinishDate", getDecideFinishDate());
		attributes.put("decideDescription", getDecideDescription());
		attributes.put("decideUserId", getDecideUserId());
		attributes.put("decideDate", getDecideDate());
		attributes.put("verifyStatus", getVerifyStatus());
		attributes.put("verifyDocNum", getVerifyDocNum());
		attributes.put("verifyDate", getVerifyDate());
		attributes.put("verifyUserId", getVerifyUserId());
		attributes.put("verifyDescription", getVerifyDescription());
		attributes.put("isActive", getIsActive());
		attributes.put("status", getStatus());
		attributes.put("createdId", getCreatedId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("modifieldId", getModifieldId());
		attributes.put("modifieldDate", getModifieldDate());
		attributes.put("infoPolicyTypeName", getInfoPolicyTypeName());
		attributes.put("infoProposeGroupName", getInfoProposeGroupName());
		attributes.put("infoVerifyGroupName", getInfoVerifyGroupName());
		attributes.put("infoResponsibleUserName", getInfoResponsibleUserName());
		attributes.put("infoInvestCreateGroupName",
			getInfoInvestCreateGroupName());
		attributes.put("infoInvestDeployGroupName",
			getInfoInvestDeployGroupName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long investPolicyId = (Long)attributes.get("investPolicyId");

		if (investPolicyId != null) {
			setInvestPolicyId(investPolicyId);
		}

		Long infoPolicyType = (Long)attributes.get("infoPolicyType");

		if (infoPolicyType != null) {
			setInfoPolicyType(infoPolicyType);
		}

		String infoPolicyName = (String)attributes.get("infoPolicyName");

		if (infoPolicyName != null) {
			setInfoPolicyName(infoPolicyName);
		}

		String infoPolicyCode = (String)attributes.get("infoPolicyCode");

		if (infoPolicyCode != null) {
			setInfoPolicyCode(infoPolicyCode);
		}

		Long infoProposeGroupId = (Long)attributes.get("infoProposeGroupId");

		if (infoProposeGroupId != null) {
			setInfoProposeGroupId(infoProposeGroupId);
		}

		Long infoVerifyGroupId = (Long)attributes.get("infoVerifyGroupId");

		if (infoVerifyGroupId != null) {
			setInfoVerifyGroupId(infoVerifyGroupId);
		}

		Date infoPolicyDate = (Date)attributes.get("infoPolicyDate");

		if (infoPolicyDate != null) {
			setInfoPolicyDate(infoPolicyDate);
		}

		Date infoPolicyDeployDate = (Date)attributes.get("infoPolicyDeployDate");

		if (infoPolicyDeployDate != null) {
			setInfoPolicyDeployDate(infoPolicyDeployDate);
		}

		Long infoResponsibleUserId = (Long)attributes.get(
				"infoResponsibleUserId");

		if (infoResponsibleUserId != null) {
			setInfoResponsibleUserId(infoResponsibleUserId);
		}

		String infoService = (String)attributes.get("infoService");

		if (infoService != null) {
			setInfoService(infoService);
		}

		String infoInvestTarget = (String)attributes.get("infoInvestTarget");

		if (infoInvestTarget != null) {
			setInfoInvestTarget(infoInvestTarget);
		}

		String infoInvestLocation = (String)attributes.get("infoInvestLocation");

		if (infoInvestLocation != null) {
			setInfoInvestLocation(infoInvestLocation);
		}

		String infoTechnique = (String)attributes.get("infoTechnique");

		if (infoTechnique != null) {
			setInfoTechnique(infoTechnique);
		}

		String infoInvestName = (String)attributes.get("infoInvestName");

		if (infoInvestName != null) {
			setInfoInvestName(infoInvestName);
		}

		Long infoInvestDeadline = (Long)attributes.get("infoInvestDeadline");

		if (infoInvestDeadline != null) {
			setInfoInvestDeadline(infoInvestDeadline);
		}

		Long infoInvestCreateGroupId = (Long)attributes.get(
				"infoInvestCreateGroupId");

		if (infoInvestCreateGroupId != null) {
			setInfoInvestCreateGroupId(infoInvestCreateGroupId);
		}

		Long infoInvestDeployGroupId = (Long)attributes.get(
				"infoInvestDeployGroupId");

		if (infoInvestDeployGroupId != null) {
			setInfoInvestDeployGroupId(infoInvestDeployGroupId);
		}

		Long costCapital = (Long)attributes.get("costCapital");

		if (costCapital != null) {
			setCostCapital(costCapital);
		}

		Double costCompensate = (Double)attributes.get("costCompensate");

		if (costCompensate != null) {
			setCostCompensate(costCompensate);
		}

		Double costCompensateForeign = (Double)attributes.get(
				"costCompensateForeign");

		if (costCompensateForeign != null) {
			setCostCompensateForeign(costCompensateForeign);
		}

		Double costEquiment = (Double)attributes.get("costEquiment");

		if (costEquiment != null) {
			setCostEquiment(costEquiment);
		}

		Double costEquimentForeign = (Double)attributes.get(
				"costEquimentForeign");

		if (costEquimentForeign != null) {
			setCostEquimentForeign(costEquimentForeign);
		}

		Double costContruction = (Double)attributes.get("costContruction");

		if (costContruction != null) {
			setCostContruction(costContruction);
		}

		Double costContructionForeign = (Double)attributes.get(
				"costContructionForeign");

		if (costContructionForeign != null) {
			setCostContructionForeign(costContructionForeign);
		}

		Double costAdvisory = (Double)attributes.get("costAdvisory");

		if (costAdvisory != null) {
			setCostAdvisory(costAdvisory);
		}

		Double costAdvisoryForeign = (Double)attributes.get(
				"costAdvisoryForeign");

		if (costAdvisoryForeign != null) {
			setCostAdvisoryForeign(costAdvisoryForeign);
		}

		Double costManager = (Double)attributes.get("costManager");

		if (costManager != null) {
			setCostManager(costManager);
		}

		Double costManagerForeign = (Double)attributes.get("costManagerForeign");

		if (costManagerForeign != null) {
			setCostManagerForeign(costManagerForeign);
		}

		Double costOther = (Double)attributes.get("costOther");

		if (costOther != null) {
			setCostOther(costOther);
		}

		Double costOtherForeign = (Double)attributes.get("costOtherForeign");

		if (costOtherForeign != null) {
			setCostOtherForeign(costOtherForeign);
		}

		Double costProvide = (Double)attributes.get("costProvide");

		if (costProvide != null) {
			setCostProvide(costProvide);
		}

		Double costProvideForeign = (Double)attributes.get("costProvideForeign");

		if (costProvideForeign != null) {
			setCostProvideForeign(costProvideForeign);
		}

		Double costLocal = (Double)attributes.get("costLocal");

		if (costLocal != null) {
			setCostLocal(costLocal);
		}

		Double costForeign = (Double)attributes.get("costForeign");

		if (costForeign != null) {
			setCostForeign(costForeign);
		}

		Double costForeignRate = (Double)attributes.get("costForeignRate");

		if (costForeignRate != null) {
			setCostForeignRate(costForeignRate);
		}

		Double costTax = (Double)attributes.get("costTax");

		if (costTax != null) {
			setCostTax(costTax);
		}

		Double costTotalValue = (Double)attributes.get("costTotalValue");

		if (costTotalValue != null) {
			setCostTotalValue(costTotalValue);
		}

		Double costTotalValueTax = (Double)attributes.get("costTotalValueTax");

		if (costTotalValueTax != null) {
			setCostTotalValueTax(costTotalValueTax);
		}

		Long decideDelivererUserId = (Long)attributes.get(
				"decideDelivererUserId");

		if (decideDelivererUserId != null) {
			setDecideDelivererUserId(decideDelivererUserId);
		}

		Long decideReceiveUserId = (Long)attributes.get("decideReceiveUserId");

		if (decideReceiveUserId != null) {
			setDecideReceiveUserId(decideReceiveUserId);
		}

		Date decideAskDate = (Date)attributes.get("decideAskDate");

		if (decideAskDate != null) {
			setDecideAskDate(decideAskDate);
		}

		Long decideDeadline = (Long)attributes.get("decideDeadline");

		if (decideDeadline != null) {
			setDecideDeadline(decideDeadline);
		}

		Date decideFinishDate = (Date)attributes.get("decideFinishDate");

		if (decideFinishDate != null) {
			setDecideFinishDate(decideFinishDate);
		}

		String decideDescription = (String)attributes.get("decideDescription");

		if (decideDescription != null) {
			setDecideDescription(decideDescription);
		}

		Long decideUserId = (Long)attributes.get("decideUserId");

		if (decideUserId != null) {
			setDecideUserId(decideUserId);
		}

		Date decideDate = (Date)attributes.get("decideDate");

		if (decideDate != null) {
			setDecideDate(decideDate);
		}

		Long verifyStatus = (Long)attributes.get("verifyStatus");

		if (verifyStatus != null) {
			setVerifyStatus(verifyStatus);
		}

		String verifyDocNum = (String)attributes.get("verifyDocNum");

		if (verifyDocNum != null) {
			setVerifyDocNum(verifyDocNum);
		}

		Date verifyDate = (Date)attributes.get("verifyDate");

		if (verifyDate != null) {
			setVerifyDate(verifyDate);
		}

		Long verifyUserId = (Long)attributes.get("verifyUserId");

		if (verifyUserId != null) {
			setVerifyUserId(verifyUserId);
		}

		String verifyDescription = (String)attributes.get("verifyDescription");

		if (verifyDescription != null) {
			setVerifyDescription(verifyDescription);
		}

		Long isActive = (Long)attributes.get("isActive");

		if (isActive != null) {
			setIsActive(isActive);
		}

		Long status = (Long)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long createdId = (Long)attributes.get("createdId");

		if (createdId != null) {
			setCreatedId(createdId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		Long modifieldId = (Long)attributes.get("modifieldId");

		if (modifieldId != null) {
			setModifieldId(modifieldId);
		}

		Date modifieldDate = (Date)attributes.get("modifieldDate");

		if (modifieldDate != null) {
			setModifieldDate(modifieldDate);
		}

		String infoPolicyTypeName = (String)attributes.get("infoPolicyTypeName");

		if (infoPolicyTypeName != null) {
			setInfoPolicyTypeName(infoPolicyTypeName);
		}

		String infoProposeGroupName = (String)attributes.get(
				"infoProposeGroupName");

		if (infoProposeGroupName != null) {
			setInfoProposeGroupName(infoProposeGroupName);
		}

		String infoVerifyGroupName = (String)attributes.get(
				"infoVerifyGroupName");

		if (infoVerifyGroupName != null) {
			setInfoVerifyGroupName(infoVerifyGroupName);
		}

		String infoResponsibleUserName = (String)attributes.get(
				"infoResponsibleUserName");

		if (infoResponsibleUserName != null) {
			setInfoResponsibleUserName(infoResponsibleUserName);
		}

		String infoInvestCreateGroupName = (String)attributes.get(
				"infoInvestCreateGroupName");

		if (infoInvestCreateGroupName != null) {
			setInfoInvestCreateGroupName(infoInvestCreateGroupName);
		}

		String infoInvestDeployGroupName = (String)attributes.get(
				"infoInvestDeployGroupName");

		if (infoInvestDeployGroupName != null) {
			setInfoInvestDeployGroupName(infoInvestDeployGroupName);
		}
	}

	@Override
	public long getInvestPolicyId() {
		return _investPolicyId;
	}

	@Override
	public void setInvestPolicyId(long investPolicyId) {
		_investPolicyId = investPolicyId;
	}

	@Override
	public long getInfoPolicyType() {
		return _infoPolicyType;
	}

	@Override
	public void setInfoPolicyType(long infoPolicyType) {
		_infoPolicyType = infoPolicyType;
	}

	@Override
	public String getInfoPolicyName() {
		if (_infoPolicyName == null) {
			return StringPool.BLANK;
		}
		else {
			return _infoPolicyName;
		}
	}

	@Override
	public void setInfoPolicyName(String infoPolicyName) {
		_columnBitmask |= INFOPOLICYNAME_COLUMN_BITMASK;

		if (_originalInfoPolicyName == null) {
			_originalInfoPolicyName = _infoPolicyName;
		}

		_infoPolicyName = infoPolicyName;
	}

	public String getOriginalInfoPolicyName() {
		return GetterUtil.getString(_originalInfoPolicyName);
	}

	@Override
	public String getInfoPolicyCode() {
		if (_infoPolicyCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _infoPolicyCode;
		}
	}

	@Override
	public void setInfoPolicyCode(String infoPolicyCode) {
		_infoPolicyCode = infoPolicyCode;
	}

	@Override
	public long getInfoProposeGroupId() {
		return _infoProposeGroupId;
	}

	@Override
	public void setInfoProposeGroupId(long infoProposeGroupId) {
		_infoProposeGroupId = infoProposeGroupId;
	}

	@Override
	public long getInfoVerifyGroupId() {
		return _infoVerifyGroupId;
	}

	@Override
	public void setInfoVerifyGroupId(long infoVerifyGroupId) {
		_infoVerifyGroupId = infoVerifyGroupId;
	}

	@Override
	public Date getInfoPolicyDate() {
		return _infoPolicyDate;
	}

	@Override
	public void setInfoPolicyDate(Date infoPolicyDate) {
		_infoPolicyDate = infoPolicyDate;
	}

	@Override
	public Date getInfoPolicyDeployDate() {
		return _infoPolicyDeployDate;
	}

	@Override
	public void setInfoPolicyDeployDate(Date infoPolicyDeployDate) {
		_infoPolicyDeployDate = infoPolicyDeployDate;
	}

	@Override
	public long getInfoResponsibleUserId() {
		return _infoResponsibleUserId;
	}

	@Override
	public void setInfoResponsibleUserId(long infoResponsibleUserId) {
		_infoResponsibleUserId = infoResponsibleUserId;
	}

	@Override
	public String getInfoResponsibleUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getInfoResponsibleUserId(), "uuid",
			_infoResponsibleUserUuid);
	}

	@Override
	public void setInfoResponsibleUserUuid(String infoResponsibleUserUuid) {
		_infoResponsibleUserUuid = infoResponsibleUserUuid;
	}

	@Override
	public String getInfoService() {
		if (_infoService == null) {
			return StringPool.BLANK;
		}
		else {
			return _infoService;
		}
	}

	@Override
	public void setInfoService(String infoService) {
		_infoService = infoService;
	}

	@Override
	public String getInfoInvestTarget() {
		if (_infoInvestTarget == null) {
			return StringPool.BLANK;
		}
		else {
			return _infoInvestTarget;
		}
	}

	@Override
	public void setInfoInvestTarget(String infoInvestTarget) {
		_infoInvestTarget = infoInvestTarget;
	}

	@Override
	public String getInfoInvestLocation() {
		if (_infoInvestLocation == null) {
			return StringPool.BLANK;
		}
		else {
			return _infoInvestLocation;
		}
	}

	@Override
	public void setInfoInvestLocation(String infoInvestLocation) {
		_infoInvestLocation = infoInvestLocation;
	}

	@Override
	public String getInfoTechnique() {
		if (_infoTechnique == null) {
			return StringPool.BLANK;
		}
		else {
			return _infoTechnique;
		}
	}

	@Override
	public void setInfoTechnique(String infoTechnique) {
		_infoTechnique = infoTechnique;
	}

	@Override
	public String getInfoInvestName() {
		if (_infoInvestName == null) {
			return StringPool.BLANK;
		}
		else {
			return _infoInvestName;
		}
	}

	@Override
	public void setInfoInvestName(String infoInvestName) {
		_infoInvestName = infoInvestName;
	}

	@Override
	public long getInfoInvestDeadline() {
		return _infoInvestDeadline;
	}

	@Override
	public void setInfoInvestDeadline(long infoInvestDeadline) {
		_infoInvestDeadline = infoInvestDeadline;
	}

	@Override
	public long getInfoInvestCreateGroupId() {
		return _infoInvestCreateGroupId;
	}

	@Override
	public void setInfoInvestCreateGroupId(long infoInvestCreateGroupId) {
		_infoInvestCreateGroupId = infoInvestCreateGroupId;
	}

	@Override
	public long getInfoInvestDeployGroupId() {
		return _infoInvestDeployGroupId;
	}

	@Override
	public void setInfoInvestDeployGroupId(long infoInvestDeployGroupId) {
		_infoInvestDeployGroupId = infoInvestDeployGroupId;
	}

	@Override
	public long getCostCapital() {
		return _costCapital;
	}

	@Override
	public void setCostCapital(long costCapital) {
		_costCapital = costCapital;
	}

	@Override
	public double getCostCompensate() {
		return _costCompensate;
	}

	@Override
	public void setCostCompensate(double costCompensate) {
		_costCompensate = costCompensate;
	}

	@Override
	public double getCostCompensateForeign() {
		return _costCompensateForeign;
	}

	@Override
	public void setCostCompensateForeign(double costCompensateForeign) {
		_costCompensateForeign = costCompensateForeign;
	}

	@Override
	public double getCostEquiment() {
		return _costEquiment;
	}

	@Override
	public void setCostEquiment(double costEquiment) {
		_costEquiment = costEquiment;
	}

	@Override
	public double getCostEquimentForeign() {
		return _costEquimentForeign;
	}

	@Override
	public void setCostEquimentForeign(double costEquimentForeign) {
		_costEquimentForeign = costEquimentForeign;
	}

	@Override
	public double getCostContruction() {
		return _costContruction;
	}

	@Override
	public void setCostContruction(double costContruction) {
		_costContruction = costContruction;
	}

	@Override
	public double getCostContructionForeign() {
		return _costContructionForeign;
	}

	@Override
	public void setCostContructionForeign(double costContructionForeign) {
		_costContructionForeign = costContructionForeign;
	}

	@Override
	public double getCostAdvisory() {
		return _costAdvisory;
	}

	@Override
	public void setCostAdvisory(double costAdvisory) {
		_costAdvisory = costAdvisory;
	}

	@Override
	public double getCostAdvisoryForeign() {
		return _costAdvisoryForeign;
	}

	@Override
	public void setCostAdvisoryForeign(double costAdvisoryForeign) {
		_costAdvisoryForeign = costAdvisoryForeign;
	}

	@Override
	public double getCostManager() {
		return _costManager;
	}

	@Override
	public void setCostManager(double costManager) {
		_costManager = costManager;
	}

	@Override
	public double getCostManagerForeign() {
		return _costManagerForeign;
	}

	@Override
	public void setCostManagerForeign(double costManagerForeign) {
		_costManagerForeign = costManagerForeign;
	}

	@Override
	public double getCostOther() {
		return _costOther;
	}

	@Override
	public void setCostOther(double costOther) {
		_costOther = costOther;
	}

	@Override
	public double getCostOtherForeign() {
		return _costOtherForeign;
	}

	@Override
	public void setCostOtherForeign(double costOtherForeign) {
		_costOtherForeign = costOtherForeign;
	}

	@Override
	public double getCostProvide() {
		return _costProvide;
	}

	@Override
	public void setCostProvide(double costProvide) {
		_costProvide = costProvide;
	}

	@Override
	public double getCostProvideForeign() {
		return _costProvideForeign;
	}

	@Override
	public void setCostProvideForeign(double costProvideForeign) {
		_costProvideForeign = costProvideForeign;
	}

	@Override
	public double getCostLocal() {
		return _costLocal;
	}

	@Override
	public void setCostLocal(double costLocal) {
		_costLocal = costLocal;
	}

	@Override
	public double getCostForeign() {
		return _costForeign;
	}

	@Override
	public void setCostForeign(double costForeign) {
		_costForeign = costForeign;
	}

	@Override
	public double getCostForeignRate() {
		return _costForeignRate;
	}

	@Override
	public void setCostForeignRate(double costForeignRate) {
		_costForeignRate = costForeignRate;
	}

	@Override
	public double getCostTax() {
		return _costTax;
	}

	@Override
	public void setCostTax(double costTax) {
		_costTax = costTax;
	}

	@Override
	public double getCostTotalValue() {
		return _costTotalValue;
	}

	@Override
	public void setCostTotalValue(double costTotalValue) {
		_costTotalValue = costTotalValue;
	}

	@Override
	public double getCostTotalValueTax() {
		return _costTotalValueTax;
	}

	@Override
	public void setCostTotalValueTax(double costTotalValueTax) {
		_costTotalValueTax = costTotalValueTax;
	}

	@Override
	public long getDecideDelivererUserId() {
		return _decideDelivererUserId;
	}

	@Override
	public void setDecideDelivererUserId(long decideDelivererUserId) {
		_decideDelivererUserId = decideDelivererUserId;
	}

	@Override
	public String getDecideDelivererUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getDecideDelivererUserId(), "uuid",
			_decideDelivererUserUuid);
	}

	@Override
	public void setDecideDelivererUserUuid(String decideDelivererUserUuid) {
		_decideDelivererUserUuid = decideDelivererUserUuid;
	}

	@Override
	public long getDecideReceiveUserId() {
		return _decideReceiveUserId;
	}

	@Override
	public void setDecideReceiveUserId(long decideReceiveUserId) {
		_decideReceiveUserId = decideReceiveUserId;
	}

	@Override
	public String getDecideReceiveUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getDecideReceiveUserId(), "uuid",
			_decideReceiveUserUuid);
	}

	@Override
	public void setDecideReceiveUserUuid(String decideReceiveUserUuid) {
		_decideReceiveUserUuid = decideReceiveUserUuid;
	}

	@Override
	public Date getDecideAskDate() {
		return _decideAskDate;
	}

	@Override
	public void setDecideAskDate(Date decideAskDate) {
		_decideAskDate = decideAskDate;
	}

	@Override
	public long getDecideDeadline() {
		return _decideDeadline;
	}

	@Override
	public void setDecideDeadline(long decideDeadline) {
		_decideDeadline = decideDeadline;
	}

	@Override
	public Date getDecideFinishDate() {
		return _decideFinishDate;
	}

	@Override
	public void setDecideFinishDate(Date decideFinishDate) {
		_decideFinishDate = decideFinishDate;
	}

	@Override
	public String getDecideDescription() {
		if (_decideDescription == null) {
			return StringPool.BLANK;
		}
		else {
			return _decideDescription;
		}
	}

	@Override
	public void setDecideDescription(String decideDescription) {
		_decideDescription = decideDescription;
	}

	@Override
	public long getDecideUserId() {
		return _decideUserId;
	}

	@Override
	public void setDecideUserId(long decideUserId) {
		_decideUserId = decideUserId;
	}

	@Override
	public String getDecideUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getDecideUserId(), "uuid",
			_decideUserUuid);
	}

	@Override
	public void setDecideUserUuid(String decideUserUuid) {
		_decideUserUuid = decideUserUuid;
	}

	@Override
	public Date getDecideDate() {
		return _decideDate;
	}

	@Override
	public void setDecideDate(Date decideDate) {
		_decideDate = decideDate;
	}

	@Override
	public long getVerifyStatus() {
		return _verifyStatus;
	}

	@Override
	public void setVerifyStatus(long verifyStatus) {
		_verifyStatus = verifyStatus;
	}

	@Override
	public String getVerifyDocNum() {
		if (_verifyDocNum == null) {
			return StringPool.BLANK;
		}
		else {
			return _verifyDocNum;
		}
	}

	@Override
	public void setVerifyDocNum(String verifyDocNum) {
		_verifyDocNum = verifyDocNum;
	}

	@Override
	public Date getVerifyDate() {
		return _verifyDate;
	}

	@Override
	public void setVerifyDate(Date verifyDate) {
		_verifyDate = verifyDate;
	}

	@Override
	public long getVerifyUserId() {
		return _verifyUserId;
	}

	@Override
	public void setVerifyUserId(long verifyUserId) {
		_verifyUserId = verifyUserId;
	}

	@Override
	public String getVerifyUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getVerifyUserId(), "uuid",
			_verifyUserUuid);
	}

	@Override
	public void setVerifyUserUuid(String verifyUserUuid) {
		_verifyUserUuid = verifyUserUuid;
	}

	@Override
	public String getVerifyDescription() {
		if (_verifyDescription == null) {
			return StringPool.BLANK;
		}
		else {
			return _verifyDescription;
		}
	}

	@Override
	public void setVerifyDescription(String verifyDescription) {
		_verifyDescription = verifyDescription;
	}

	@Override
	public long getIsActive() {
		return _isActive;
	}

	@Override
	public void setIsActive(long isActive) {
		_columnBitmask |= ISACTIVE_COLUMN_BITMASK;

		if (!_setOriginalIsActive) {
			_setOriginalIsActive = true;

			_originalIsActive = _isActive;
		}

		_isActive = isActive;
	}

	public long getOriginalIsActive() {
		return _originalIsActive;
	}

	@Override
	public long getStatus() {
		return _status;
	}

	@Override
	public void setStatus(long status) {
		_status = status;
	}

	@Override
	public long getCreatedId() {
		return _createdId;
	}

	@Override
	public void setCreatedId(long createdId) {
		_createdId = createdId;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_columnBitmask = -1L;

		_createdDate = createdDate;
	}

	@Override
	public long getModifieldId() {
		return _modifieldId;
	}

	@Override
	public void setModifieldId(long modifieldId) {
		_modifieldId = modifieldId;
	}

	@Override
	public Date getModifieldDate() {
		return _modifieldDate;
	}

	@Override
	public void setModifieldDate(Date modifieldDate) {
		_modifieldDate = modifieldDate;
	}

	@Override
	public String getInfoPolicyTypeName() {
		if (_infoPolicyTypeName == null) {
			return StringPool.BLANK;
		}
		else {
			return _infoPolicyTypeName;
		}
	}

	@Override
	public void setInfoPolicyTypeName(String infoPolicyTypeName) {
		_infoPolicyTypeName = infoPolicyTypeName;
	}

	@Override
	public String getInfoProposeGroupName() {
		if (_infoProposeGroupName == null) {
			return StringPool.BLANK;
		}
		else {
			return _infoProposeGroupName;
		}
	}

	@Override
	public void setInfoProposeGroupName(String infoProposeGroupName) {
		_infoProposeGroupName = infoProposeGroupName;
	}

	@Override
	public String getInfoVerifyGroupName() {
		if (_infoVerifyGroupName == null) {
			return StringPool.BLANK;
		}
		else {
			return _infoVerifyGroupName;
		}
	}

	@Override
	public void setInfoVerifyGroupName(String infoVerifyGroupName) {
		_infoVerifyGroupName = infoVerifyGroupName;
	}

	@Override
	public String getInfoResponsibleUserName() {
		if (_infoResponsibleUserName == null) {
			return StringPool.BLANK;
		}
		else {
			return _infoResponsibleUserName;
		}
	}

	@Override
	public void setInfoResponsibleUserName(String infoResponsibleUserName) {
		_infoResponsibleUserName = infoResponsibleUserName;
	}

	@Override
	public String getInfoInvestCreateGroupName() {
		if (_infoInvestCreateGroupName == null) {
			return StringPool.BLANK;
		}
		else {
			return _infoInvestCreateGroupName;
		}
	}

	@Override
	public void setInfoInvestCreateGroupName(String infoInvestCreateGroupName) {
		_infoInvestCreateGroupName = infoInvestCreateGroupName;
	}

	@Override
	public String getInfoInvestDeployGroupName() {
		if (_infoInvestDeployGroupName == null) {
			return StringPool.BLANK;
		}
		else {
			return _infoInvestDeployGroupName;
		}
	}

	@Override
	public void setInfoInvestDeployGroupName(String infoInvestDeployGroupName) {
		_infoInvestDeployGroupName = infoInvestDeployGroupName;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			InvestPolicyExt.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public InvestPolicyExt toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (InvestPolicyExt)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		InvestPolicyExtImpl investPolicyExtImpl = new InvestPolicyExtImpl();

		investPolicyExtImpl.setInvestPolicyId(getInvestPolicyId());
		investPolicyExtImpl.setInfoPolicyType(getInfoPolicyType());
		investPolicyExtImpl.setInfoPolicyName(getInfoPolicyName());
		investPolicyExtImpl.setInfoPolicyCode(getInfoPolicyCode());
		investPolicyExtImpl.setInfoProposeGroupId(getInfoProposeGroupId());
		investPolicyExtImpl.setInfoVerifyGroupId(getInfoVerifyGroupId());
		investPolicyExtImpl.setInfoPolicyDate(getInfoPolicyDate());
		investPolicyExtImpl.setInfoPolicyDeployDate(getInfoPolicyDeployDate());
		investPolicyExtImpl.setInfoResponsibleUserId(getInfoResponsibleUserId());
		investPolicyExtImpl.setInfoService(getInfoService());
		investPolicyExtImpl.setInfoInvestTarget(getInfoInvestTarget());
		investPolicyExtImpl.setInfoInvestLocation(getInfoInvestLocation());
		investPolicyExtImpl.setInfoTechnique(getInfoTechnique());
		investPolicyExtImpl.setInfoInvestName(getInfoInvestName());
		investPolicyExtImpl.setInfoInvestDeadline(getInfoInvestDeadline());
		investPolicyExtImpl.setInfoInvestCreateGroupId(getInfoInvestCreateGroupId());
		investPolicyExtImpl.setInfoInvestDeployGroupId(getInfoInvestDeployGroupId());
		investPolicyExtImpl.setCostCapital(getCostCapital());
		investPolicyExtImpl.setCostCompensate(getCostCompensate());
		investPolicyExtImpl.setCostCompensateForeign(getCostCompensateForeign());
		investPolicyExtImpl.setCostEquiment(getCostEquiment());
		investPolicyExtImpl.setCostEquimentForeign(getCostEquimentForeign());
		investPolicyExtImpl.setCostContruction(getCostContruction());
		investPolicyExtImpl.setCostContructionForeign(getCostContructionForeign());
		investPolicyExtImpl.setCostAdvisory(getCostAdvisory());
		investPolicyExtImpl.setCostAdvisoryForeign(getCostAdvisoryForeign());
		investPolicyExtImpl.setCostManager(getCostManager());
		investPolicyExtImpl.setCostManagerForeign(getCostManagerForeign());
		investPolicyExtImpl.setCostOther(getCostOther());
		investPolicyExtImpl.setCostOtherForeign(getCostOtherForeign());
		investPolicyExtImpl.setCostProvide(getCostProvide());
		investPolicyExtImpl.setCostProvideForeign(getCostProvideForeign());
		investPolicyExtImpl.setCostLocal(getCostLocal());
		investPolicyExtImpl.setCostForeign(getCostForeign());
		investPolicyExtImpl.setCostForeignRate(getCostForeignRate());
		investPolicyExtImpl.setCostTax(getCostTax());
		investPolicyExtImpl.setCostTotalValue(getCostTotalValue());
		investPolicyExtImpl.setCostTotalValueTax(getCostTotalValueTax());
		investPolicyExtImpl.setDecideDelivererUserId(getDecideDelivererUserId());
		investPolicyExtImpl.setDecideReceiveUserId(getDecideReceiveUserId());
		investPolicyExtImpl.setDecideAskDate(getDecideAskDate());
		investPolicyExtImpl.setDecideDeadline(getDecideDeadline());
		investPolicyExtImpl.setDecideFinishDate(getDecideFinishDate());
		investPolicyExtImpl.setDecideDescription(getDecideDescription());
		investPolicyExtImpl.setDecideUserId(getDecideUserId());
		investPolicyExtImpl.setDecideDate(getDecideDate());
		investPolicyExtImpl.setVerifyStatus(getVerifyStatus());
		investPolicyExtImpl.setVerifyDocNum(getVerifyDocNum());
		investPolicyExtImpl.setVerifyDate(getVerifyDate());
		investPolicyExtImpl.setVerifyUserId(getVerifyUserId());
		investPolicyExtImpl.setVerifyDescription(getVerifyDescription());
		investPolicyExtImpl.setIsActive(getIsActive());
		investPolicyExtImpl.setStatus(getStatus());
		investPolicyExtImpl.setCreatedId(getCreatedId());
		investPolicyExtImpl.setCreatedDate(getCreatedDate());
		investPolicyExtImpl.setModifieldId(getModifieldId());
		investPolicyExtImpl.setModifieldDate(getModifieldDate());
		investPolicyExtImpl.setInfoPolicyTypeName(getInfoPolicyTypeName());
		investPolicyExtImpl.setInfoProposeGroupName(getInfoProposeGroupName());
		investPolicyExtImpl.setInfoVerifyGroupName(getInfoVerifyGroupName());
		investPolicyExtImpl.setInfoResponsibleUserName(getInfoResponsibleUserName());
		investPolicyExtImpl.setInfoInvestCreateGroupName(getInfoInvestCreateGroupName());
		investPolicyExtImpl.setInfoInvestDeployGroupName(getInfoInvestDeployGroupName());

		investPolicyExtImpl.resetOriginalValues();

		return investPolicyExtImpl;
	}

	@Override
	public int compareTo(InvestPolicyExt investPolicyExt) {
		int value = 0;

		value = DateUtil.compareTo(getCreatedDate(),
				investPolicyExt.getCreatedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof InvestPolicyExt)) {
			return false;
		}

		InvestPolicyExt investPolicyExt = (InvestPolicyExt)obj;

		long primaryKey = investPolicyExt.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		InvestPolicyExtModelImpl investPolicyExtModelImpl = this;

		investPolicyExtModelImpl._originalInfoPolicyName = investPolicyExtModelImpl._infoPolicyName;

		investPolicyExtModelImpl._originalIsActive = investPolicyExtModelImpl._isActive;

		investPolicyExtModelImpl._setOriginalIsActive = false;

		investPolicyExtModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<InvestPolicyExt> toCacheModel() {
		InvestPolicyExtCacheModel investPolicyExtCacheModel = new InvestPolicyExtCacheModel();

		investPolicyExtCacheModel.investPolicyId = getInvestPolicyId();

		investPolicyExtCacheModel.infoPolicyType = getInfoPolicyType();

		investPolicyExtCacheModel.infoPolicyName = getInfoPolicyName();

		String infoPolicyName = investPolicyExtCacheModel.infoPolicyName;

		if ((infoPolicyName != null) && (infoPolicyName.length() == 0)) {
			investPolicyExtCacheModel.infoPolicyName = null;
		}

		investPolicyExtCacheModel.infoPolicyCode = getInfoPolicyCode();

		String infoPolicyCode = investPolicyExtCacheModel.infoPolicyCode;

		if ((infoPolicyCode != null) && (infoPolicyCode.length() == 0)) {
			investPolicyExtCacheModel.infoPolicyCode = null;
		}

		investPolicyExtCacheModel.infoProposeGroupId = getInfoProposeGroupId();

		investPolicyExtCacheModel.infoVerifyGroupId = getInfoVerifyGroupId();

		Date infoPolicyDate = getInfoPolicyDate();

		if (infoPolicyDate != null) {
			investPolicyExtCacheModel.infoPolicyDate = infoPolicyDate.getTime();
		}
		else {
			investPolicyExtCacheModel.infoPolicyDate = Long.MIN_VALUE;
		}

		Date infoPolicyDeployDate = getInfoPolicyDeployDate();

		if (infoPolicyDeployDate != null) {
			investPolicyExtCacheModel.infoPolicyDeployDate = infoPolicyDeployDate.getTime();
		}
		else {
			investPolicyExtCacheModel.infoPolicyDeployDate = Long.MIN_VALUE;
		}

		investPolicyExtCacheModel.infoResponsibleUserId = getInfoResponsibleUserId();

		investPolicyExtCacheModel.infoService = getInfoService();

		String infoService = investPolicyExtCacheModel.infoService;

		if ((infoService != null) && (infoService.length() == 0)) {
			investPolicyExtCacheModel.infoService = null;
		}

		investPolicyExtCacheModel.infoInvestTarget = getInfoInvestTarget();

		String infoInvestTarget = investPolicyExtCacheModel.infoInvestTarget;

		if ((infoInvestTarget != null) && (infoInvestTarget.length() == 0)) {
			investPolicyExtCacheModel.infoInvestTarget = null;
		}

		investPolicyExtCacheModel.infoInvestLocation = getInfoInvestLocation();

		String infoInvestLocation = investPolicyExtCacheModel.infoInvestLocation;

		if ((infoInvestLocation != null) && (infoInvestLocation.length() == 0)) {
			investPolicyExtCacheModel.infoInvestLocation = null;
		}

		investPolicyExtCacheModel.infoTechnique = getInfoTechnique();

		String infoTechnique = investPolicyExtCacheModel.infoTechnique;

		if ((infoTechnique != null) && (infoTechnique.length() == 0)) {
			investPolicyExtCacheModel.infoTechnique = null;
		}

		investPolicyExtCacheModel.infoInvestName = getInfoInvestName();

		String infoInvestName = investPolicyExtCacheModel.infoInvestName;

		if ((infoInvestName != null) && (infoInvestName.length() == 0)) {
			investPolicyExtCacheModel.infoInvestName = null;
		}

		investPolicyExtCacheModel.infoInvestDeadline = getInfoInvestDeadline();

		investPolicyExtCacheModel.infoInvestCreateGroupId = getInfoInvestCreateGroupId();

		investPolicyExtCacheModel.infoInvestDeployGroupId = getInfoInvestDeployGroupId();

		investPolicyExtCacheModel.costCapital = getCostCapital();

		investPolicyExtCacheModel.costCompensate = getCostCompensate();

		investPolicyExtCacheModel.costCompensateForeign = getCostCompensateForeign();

		investPolicyExtCacheModel.costEquiment = getCostEquiment();

		investPolicyExtCacheModel.costEquimentForeign = getCostEquimentForeign();

		investPolicyExtCacheModel.costContruction = getCostContruction();

		investPolicyExtCacheModel.costContructionForeign = getCostContructionForeign();

		investPolicyExtCacheModel.costAdvisory = getCostAdvisory();

		investPolicyExtCacheModel.costAdvisoryForeign = getCostAdvisoryForeign();

		investPolicyExtCacheModel.costManager = getCostManager();

		investPolicyExtCacheModel.costManagerForeign = getCostManagerForeign();

		investPolicyExtCacheModel.costOther = getCostOther();

		investPolicyExtCacheModel.costOtherForeign = getCostOtherForeign();

		investPolicyExtCacheModel.costProvide = getCostProvide();

		investPolicyExtCacheModel.costProvideForeign = getCostProvideForeign();

		investPolicyExtCacheModel.costLocal = getCostLocal();

		investPolicyExtCacheModel.costForeign = getCostForeign();

		investPolicyExtCacheModel.costForeignRate = getCostForeignRate();

		investPolicyExtCacheModel.costTax = getCostTax();

		investPolicyExtCacheModel.costTotalValue = getCostTotalValue();

		investPolicyExtCacheModel.costTotalValueTax = getCostTotalValueTax();

		investPolicyExtCacheModel.decideDelivererUserId = getDecideDelivererUserId();

		investPolicyExtCacheModel.decideReceiveUserId = getDecideReceiveUserId();

		Date decideAskDate = getDecideAskDate();

		if (decideAskDate != null) {
			investPolicyExtCacheModel.decideAskDate = decideAskDate.getTime();
		}
		else {
			investPolicyExtCacheModel.decideAskDate = Long.MIN_VALUE;
		}

		investPolicyExtCacheModel.decideDeadline = getDecideDeadline();

		Date decideFinishDate = getDecideFinishDate();

		if (decideFinishDate != null) {
			investPolicyExtCacheModel.decideFinishDate = decideFinishDate.getTime();
		}
		else {
			investPolicyExtCacheModel.decideFinishDate = Long.MIN_VALUE;
		}

		investPolicyExtCacheModel.decideDescription = getDecideDescription();

		String decideDescription = investPolicyExtCacheModel.decideDescription;

		if ((decideDescription != null) && (decideDescription.length() == 0)) {
			investPolicyExtCacheModel.decideDescription = null;
		}

		investPolicyExtCacheModel.decideUserId = getDecideUserId();

		Date decideDate = getDecideDate();

		if (decideDate != null) {
			investPolicyExtCacheModel.decideDate = decideDate.getTime();
		}
		else {
			investPolicyExtCacheModel.decideDate = Long.MIN_VALUE;
		}

		investPolicyExtCacheModel.verifyStatus = getVerifyStatus();

		investPolicyExtCacheModel.verifyDocNum = getVerifyDocNum();

		String verifyDocNum = investPolicyExtCacheModel.verifyDocNum;

		if ((verifyDocNum != null) && (verifyDocNum.length() == 0)) {
			investPolicyExtCacheModel.verifyDocNum = null;
		}

		Date verifyDate = getVerifyDate();

		if (verifyDate != null) {
			investPolicyExtCacheModel.verifyDate = verifyDate.getTime();
		}
		else {
			investPolicyExtCacheModel.verifyDate = Long.MIN_VALUE;
		}

		investPolicyExtCacheModel.verifyUserId = getVerifyUserId();

		investPolicyExtCacheModel.verifyDescription = getVerifyDescription();

		String verifyDescription = investPolicyExtCacheModel.verifyDescription;

		if ((verifyDescription != null) && (verifyDescription.length() == 0)) {
			investPolicyExtCacheModel.verifyDescription = null;
		}

		investPolicyExtCacheModel.isActive = getIsActive();

		investPolicyExtCacheModel.status = getStatus();

		investPolicyExtCacheModel.createdId = getCreatedId();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			investPolicyExtCacheModel.createdDate = createdDate.getTime();
		}
		else {
			investPolicyExtCacheModel.createdDate = Long.MIN_VALUE;
		}

		investPolicyExtCacheModel.modifieldId = getModifieldId();

		Date modifieldDate = getModifieldDate();

		if (modifieldDate != null) {
			investPolicyExtCacheModel.modifieldDate = modifieldDate.getTime();
		}
		else {
			investPolicyExtCacheModel.modifieldDate = Long.MIN_VALUE;
		}

		investPolicyExtCacheModel.infoPolicyTypeName = getInfoPolicyTypeName();

		String infoPolicyTypeName = investPolicyExtCacheModel.infoPolicyTypeName;

		if ((infoPolicyTypeName != null) && (infoPolicyTypeName.length() == 0)) {
			investPolicyExtCacheModel.infoPolicyTypeName = null;
		}

		investPolicyExtCacheModel.infoProposeGroupName = getInfoProposeGroupName();

		String infoProposeGroupName = investPolicyExtCacheModel.infoProposeGroupName;

		if ((infoProposeGroupName != null) &&
				(infoProposeGroupName.length() == 0)) {
			investPolicyExtCacheModel.infoProposeGroupName = null;
		}

		investPolicyExtCacheModel.infoVerifyGroupName = getInfoVerifyGroupName();

		String infoVerifyGroupName = investPolicyExtCacheModel.infoVerifyGroupName;

		if ((infoVerifyGroupName != null) &&
				(infoVerifyGroupName.length() == 0)) {
			investPolicyExtCacheModel.infoVerifyGroupName = null;
		}

		investPolicyExtCacheModel.infoResponsibleUserName = getInfoResponsibleUserName();

		String infoResponsibleUserName = investPolicyExtCacheModel.infoResponsibleUserName;

		if ((infoResponsibleUserName != null) &&
				(infoResponsibleUserName.length() == 0)) {
			investPolicyExtCacheModel.infoResponsibleUserName = null;
		}

		investPolicyExtCacheModel.infoInvestCreateGroupName = getInfoInvestCreateGroupName();

		String infoInvestCreateGroupName = investPolicyExtCacheModel.infoInvestCreateGroupName;

		if ((infoInvestCreateGroupName != null) &&
				(infoInvestCreateGroupName.length() == 0)) {
			investPolicyExtCacheModel.infoInvestCreateGroupName = null;
		}

		investPolicyExtCacheModel.infoInvestDeployGroupName = getInfoInvestDeployGroupName();

		String infoInvestDeployGroupName = investPolicyExtCacheModel.infoInvestDeployGroupName;

		if ((infoInvestDeployGroupName != null) &&
				(infoInvestDeployGroupName.length() == 0)) {
			investPolicyExtCacheModel.infoInvestDeployGroupName = null;
		}

		return investPolicyExtCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(127);

		sb.append("{investPolicyId=");
		sb.append(getInvestPolicyId());
		sb.append(", infoPolicyType=");
		sb.append(getInfoPolicyType());
		sb.append(", infoPolicyName=");
		sb.append(getInfoPolicyName());
		sb.append(", infoPolicyCode=");
		sb.append(getInfoPolicyCode());
		sb.append(", infoProposeGroupId=");
		sb.append(getInfoProposeGroupId());
		sb.append(", infoVerifyGroupId=");
		sb.append(getInfoVerifyGroupId());
		sb.append(", infoPolicyDate=");
		sb.append(getInfoPolicyDate());
		sb.append(", infoPolicyDeployDate=");
		sb.append(getInfoPolicyDeployDate());
		sb.append(", infoResponsibleUserId=");
		sb.append(getInfoResponsibleUserId());
		sb.append(", infoService=");
		sb.append(getInfoService());
		sb.append(", infoInvestTarget=");
		sb.append(getInfoInvestTarget());
		sb.append(", infoInvestLocation=");
		sb.append(getInfoInvestLocation());
		sb.append(", infoTechnique=");
		sb.append(getInfoTechnique());
		sb.append(", infoInvestName=");
		sb.append(getInfoInvestName());
		sb.append(", infoInvestDeadline=");
		sb.append(getInfoInvestDeadline());
		sb.append(", infoInvestCreateGroupId=");
		sb.append(getInfoInvestCreateGroupId());
		sb.append(", infoInvestDeployGroupId=");
		sb.append(getInfoInvestDeployGroupId());
		sb.append(", costCapital=");
		sb.append(getCostCapital());
		sb.append(", costCompensate=");
		sb.append(getCostCompensate());
		sb.append(", costCompensateForeign=");
		sb.append(getCostCompensateForeign());
		sb.append(", costEquiment=");
		sb.append(getCostEquiment());
		sb.append(", costEquimentForeign=");
		sb.append(getCostEquimentForeign());
		sb.append(", costContruction=");
		sb.append(getCostContruction());
		sb.append(", costContructionForeign=");
		sb.append(getCostContructionForeign());
		sb.append(", costAdvisory=");
		sb.append(getCostAdvisory());
		sb.append(", costAdvisoryForeign=");
		sb.append(getCostAdvisoryForeign());
		sb.append(", costManager=");
		sb.append(getCostManager());
		sb.append(", costManagerForeign=");
		sb.append(getCostManagerForeign());
		sb.append(", costOther=");
		sb.append(getCostOther());
		sb.append(", costOtherForeign=");
		sb.append(getCostOtherForeign());
		sb.append(", costProvide=");
		sb.append(getCostProvide());
		sb.append(", costProvideForeign=");
		sb.append(getCostProvideForeign());
		sb.append(", costLocal=");
		sb.append(getCostLocal());
		sb.append(", costForeign=");
		sb.append(getCostForeign());
		sb.append(", costForeignRate=");
		sb.append(getCostForeignRate());
		sb.append(", costTax=");
		sb.append(getCostTax());
		sb.append(", costTotalValue=");
		sb.append(getCostTotalValue());
		sb.append(", costTotalValueTax=");
		sb.append(getCostTotalValueTax());
		sb.append(", decideDelivererUserId=");
		sb.append(getDecideDelivererUserId());
		sb.append(", decideReceiveUserId=");
		sb.append(getDecideReceiveUserId());
		sb.append(", decideAskDate=");
		sb.append(getDecideAskDate());
		sb.append(", decideDeadline=");
		sb.append(getDecideDeadline());
		sb.append(", decideFinishDate=");
		sb.append(getDecideFinishDate());
		sb.append(", decideDescription=");
		sb.append(getDecideDescription());
		sb.append(", decideUserId=");
		sb.append(getDecideUserId());
		sb.append(", decideDate=");
		sb.append(getDecideDate());
		sb.append(", verifyStatus=");
		sb.append(getVerifyStatus());
		sb.append(", verifyDocNum=");
		sb.append(getVerifyDocNum());
		sb.append(", verifyDate=");
		sb.append(getVerifyDate());
		sb.append(", verifyUserId=");
		sb.append(getVerifyUserId());
		sb.append(", verifyDescription=");
		sb.append(getVerifyDescription());
		sb.append(", isActive=");
		sb.append(getIsActive());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", createdId=");
		sb.append(getCreatedId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", modifieldId=");
		sb.append(getModifieldId());
		sb.append(", modifieldDate=");
		sb.append(getModifieldDate());
		sb.append(", infoPolicyTypeName=");
		sb.append(getInfoPolicyTypeName());
		sb.append(", infoProposeGroupName=");
		sb.append(getInfoProposeGroupName());
		sb.append(", infoVerifyGroupName=");
		sb.append(getInfoVerifyGroupName());
		sb.append(", infoResponsibleUserName=");
		sb.append(getInfoResponsibleUserName());
		sb.append(", infoInvestCreateGroupName=");
		sb.append(getInfoInvestCreateGroupName());
		sb.append(", infoInvestDeployGroupName=");
		sb.append(getInfoInvestDeployGroupName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(193);

		sb.append("<model><model-name>");
		sb.append("com.viettel.ims.core.model.InvestPolicyExt");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>investPolicyId</column-name><column-value><![CDATA[");
		sb.append(getInvestPolicyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoPolicyType</column-name><column-value><![CDATA[");
		sb.append(getInfoPolicyType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoPolicyName</column-name><column-value><![CDATA[");
		sb.append(getInfoPolicyName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoPolicyCode</column-name><column-value><![CDATA[");
		sb.append(getInfoPolicyCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoProposeGroupId</column-name><column-value><![CDATA[");
		sb.append(getInfoProposeGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoVerifyGroupId</column-name><column-value><![CDATA[");
		sb.append(getInfoVerifyGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoPolicyDate</column-name><column-value><![CDATA[");
		sb.append(getInfoPolicyDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoPolicyDeployDate</column-name><column-value><![CDATA[");
		sb.append(getInfoPolicyDeployDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoResponsibleUserId</column-name><column-value><![CDATA[");
		sb.append(getInfoResponsibleUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoService</column-name><column-value><![CDATA[");
		sb.append(getInfoService());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoInvestTarget</column-name><column-value><![CDATA[");
		sb.append(getInfoInvestTarget());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoInvestLocation</column-name><column-value><![CDATA[");
		sb.append(getInfoInvestLocation());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoTechnique</column-name><column-value><![CDATA[");
		sb.append(getInfoTechnique());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoInvestName</column-name><column-value><![CDATA[");
		sb.append(getInfoInvestName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoInvestDeadline</column-name><column-value><![CDATA[");
		sb.append(getInfoInvestDeadline());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoInvestCreateGroupId</column-name><column-value><![CDATA[");
		sb.append(getInfoInvestCreateGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoInvestDeployGroupId</column-name><column-value><![CDATA[");
		sb.append(getInfoInvestDeployGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costCapital</column-name><column-value><![CDATA[");
		sb.append(getCostCapital());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costCompensate</column-name><column-value><![CDATA[");
		sb.append(getCostCompensate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costCompensateForeign</column-name><column-value><![CDATA[");
		sb.append(getCostCompensateForeign());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costEquiment</column-name><column-value><![CDATA[");
		sb.append(getCostEquiment());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costEquimentForeign</column-name><column-value><![CDATA[");
		sb.append(getCostEquimentForeign());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costContruction</column-name><column-value><![CDATA[");
		sb.append(getCostContruction());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costContructionForeign</column-name><column-value><![CDATA[");
		sb.append(getCostContructionForeign());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costAdvisory</column-name><column-value><![CDATA[");
		sb.append(getCostAdvisory());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costAdvisoryForeign</column-name><column-value><![CDATA[");
		sb.append(getCostAdvisoryForeign());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costManager</column-name><column-value><![CDATA[");
		sb.append(getCostManager());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costManagerForeign</column-name><column-value><![CDATA[");
		sb.append(getCostManagerForeign());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costOther</column-name><column-value><![CDATA[");
		sb.append(getCostOther());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costOtherForeign</column-name><column-value><![CDATA[");
		sb.append(getCostOtherForeign());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costProvide</column-name><column-value><![CDATA[");
		sb.append(getCostProvide());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costProvideForeign</column-name><column-value><![CDATA[");
		sb.append(getCostProvideForeign());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costLocal</column-name><column-value><![CDATA[");
		sb.append(getCostLocal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costForeign</column-name><column-value><![CDATA[");
		sb.append(getCostForeign());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costForeignRate</column-name><column-value><![CDATA[");
		sb.append(getCostForeignRate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costTax</column-name><column-value><![CDATA[");
		sb.append(getCostTax());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costTotalValue</column-name><column-value><![CDATA[");
		sb.append(getCostTotalValue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costTotalValueTax</column-name><column-value><![CDATA[");
		sb.append(getCostTotalValueTax());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>decideDelivererUserId</column-name><column-value><![CDATA[");
		sb.append(getDecideDelivererUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>decideReceiveUserId</column-name><column-value><![CDATA[");
		sb.append(getDecideReceiveUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>decideAskDate</column-name><column-value><![CDATA[");
		sb.append(getDecideAskDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>decideDeadline</column-name><column-value><![CDATA[");
		sb.append(getDecideDeadline());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>decideFinishDate</column-name><column-value><![CDATA[");
		sb.append(getDecideFinishDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>decideDescription</column-name><column-value><![CDATA[");
		sb.append(getDecideDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>decideUserId</column-name><column-value><![CDATA[");
		sb.append(getDecideUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>decideDate</column-name><column-value><![CDATA[");
		sb.append(getDecideDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>verifyStatus</column-name><column-value><![CDATA[");
		sb.append(getVerifyStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>verifyDocNum</column-name><column-value><![CDATA[");
		sb.append(getVerifyDocNum());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>verifyDate</column-name><column-value><![CDATA[");
		sb.append(getVerifyDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>verifyUserId</column-name><column-value><![CDATA[");
		sb.append(getVerifyUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>verifyDescription</column-name><column-value><![CDATA[");
		sb.append(getVerifyDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isActive</column-name><column-value><![CDATA[");
		sb.append(getIsActive());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdId</column-name><column-value><![CDATA[");
		sb.append(getCreatedId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifieldId</column-name><column-value><![CDATA[");
		sb.append(getModifieldId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifieldDate</column-name><column-value><![CDATA[");
		sb.append(getModifieldDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoPolicyTypeName</column-name><column-value><![CDATA[");
		sb.append(getInfoPolicyTypeName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoProposeGroupName</column-name><column-value><![CDATA[");
		sb.append(getInfoProposeGroupName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoVerifyGroupName</column-name><column-value><![CDATA[");
		sb.append(getInfoVerifyGroupName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoResponsibleUserName</column-name><column-value><![CDATA[");
		sb.append(getInfoResponsibleUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoInvestCreateGroupName</column-name><column-value><![CDATA[");
		sb.append(getInfoInvestCreateGroupName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoInvestDeployGroupName</column-name><column-value><![CDATA[");
		sb.append(getInfoInvestDeployGroupName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = InvestPolicyExt.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			InvestPolicyExt.class
		};
	private long _investPolicyId;
	private long _infoPolicyType;
	private String _infoPolicyName;
	private String _originalInfoPolicyName;
	private String _infoPolicyCode;
	private long _infoProposeGroupId;
	private long _infoVerifyGroupId;
	private Date _infoPolicyDate;
	private Date _infoPolicyDeployDate;
	private long _infoResponsibleUserId;
	private String _infoResponsibleUserUuid;
	private String _infoService;
	private String _infoInvestTarget;
	private String _infoInvestLocation;
	private String _infoTechnique;
	private String _infoInvestName;
	private long _infoInvestDeadline;
	private long _infoInvestCreateGroupId;
	private long _infoInvestDeployGroupId;
	private long _costCapital;
	private double _costCompensate;
	private double _costCompensateForeign;
	private double _costEquiment;
	private double _costEquimentForeign;
	private double _costContruction;
	private double _costContructionForeign;
	private double _costAdvisory;
	private double _costAdvisoryForeign;
	private double _costManager;
	private double _costManagerForeign;
	private double _costOther;
	private double _costOtherForeign;
	private double _costProvide;
	private double _costProvideForeign;
	private double _costLocal;
	private double _costForeign;
	private double _costForeignRate;
	private double _costTax;
	private double _costTotalValue;
	private double _costTotalValueTax;
	private long _decideDelivererUserId;
	private String _decideDelivererUserUuid;
	private long _decideReceiveUserId;
	private String _decideReceiveUserUuid;
	private Date _decideAskDate;
	private long _decideDeadline;
	private Date _decideFinishDate;
	private String _decideDescription;
	private long _decideUserId;
	private String _decideUserUuid;
	private Date _decideDate;
	private long _verifyStatus;
	private String _verifyDocNum;
	private Date _verifyDate;
	private long _verifyUserId;
	private String _verifyUserUuid;
	private String _verifyDescription;
	private long _isActive;
	private long _originalIsActive;
	private boolean _setOriginalIsActive;
	private long _status;
	private long _createdId;
	private Date _createdDate;
	private long _modifieldId;
	private Date _modifieldDate;
	private String _infoPolicyTypeName;
	private String _infoProposeGroupName;
	private String _infoVerifyGroupName;
	private String _infoResponsibleUserName;
	private String _infoInvestCreateGroupName;
	private String _infoInvestDeployGroupName;
	private long _columnBitmask;
	private InvestPolicyExt _escapedModel;
}