/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.viettel.ims.core.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.viettel.ims.core.model.VInvestPolicy;
import com.viettel.ims.core.model.VInvestPolicyModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VInvestPolicy service. Represents a row in the &quot;V_INVEST_POLICY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.viettel.ims.core.model.VInvestPolicyModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VInvestPolicyImpl}.
 * </p>
 *
 * @author MrNet
 * @see VInvestPolicyImpl
 * @see com.viettel.ims.core.model.VInvestPolicy
 * @see com.viettel.ims.core.model.VInvestPolicyModel
 * @generated
 */
public class VInvestPolicyModelImpl extends BaseModelImpl<VInvestPolicy>
	implements VInvestPolicyModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a v invest policy model instance should use the {@link com.viettel.ims.core.model.VInvestPolicy} interface instead.
	 */
	public static final String TABLE_NAME = "V_INVEST_POLICY";
	public static final Object[][] TABLE_COLUMNS = {
			{ "invest_policy_id", Types.BIGINT },
			{ "infoPolicyTypeName", Types.VARCHAR },
			{ "infoPolicyName", Types.VARCHAR },
			{ "infoProposeGroupName", Types.VARCHAR },
			{ "infoVerifyGroupName", Types.VARCHAR },
			{ "infoPolicyDate", Types.TIMESTAMP },
			{ "infoPolicyDeployDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table V_INVEST_POLICY (invest_policy_id LONG not null primary key,infoPolicyTypeName VARCHAR(75) null,infoPolicyName VARCHAR(75) null,infoProposeGroupName VARCHAR(75) null,infoVerifyGroupName VARCHAR(75) null,infoPolicyDate DATE null,infoPolicyDeployDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table V_INVEST_POLICY";
	public static final String ORDER_BY_JPQL = " ORDER BY vInvestPolicy.investPolicyId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY V_INVEST_POLICY.invest_policy_id ASC";
	public static final String DATA_SOURCE = "imsDataSource";
	public static final String SESSION_FACTORY = "imsSessionFactory";
	public static final String TX_MANAGER = "imsTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.viettel.ims.core.model.VInvestPolicy"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.viettel.ims.core.model.VInvestPolicy"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.viettel.ims.core.model.VInvestPolicy"));

	public VInvestPolicyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _investPolicyId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setInvestPolicyId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _investPolicyId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VInvestPolicy.class;
	}

	@Override
	public String getModelClassName() {
		return VInvestPolicy.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("investPolicyId", getInvestPolicyId());
		attributes.put("infoPolicyTypeName", getInfoPolicyTypeName());
		attributes.put("infoPolicyName", getInfoPolicyName());
		attributes.put("infoProposeGroupName", getInfoProposeGroupName());
		attributes.put("infoVerifyGroupName", getInfoVerifyGroupName());
		attributes.put("infoPolicyDate", getInfoPolicyDate());
		attributes.put("infoPolicyDeployDate", getInfoPolicyDeployDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long investPolicyId = (Long)attributes.get("investPolicyId");

		if (investPolicyId != null) {
			setInvestPolicyId(investPolicyId);
		}

		String infoPolicyTypeName = (String)attributes.get("infoPolicyTypeName");

		if (infoPolicyTypeName != null) {
			setInfoPolicyTypeName(infoPolicyTypeName);
		}

		String infoPolicyName = (String)attributes.get("infoPolicyName");

		if (infoPolicyName != null) {
			setInfoPolicyName(infoPolicyName);
		}

		String infoProposeGroupName = (String)attributes.get(
				"infoProposeGroupName");

		if (infoProposeGroupName != null) {
			setInfoProposeGroupName(infoProposeGroupName);
		}

		String infoVerifyGroupName = (String)attributes.get(
				"infoVerifyGroupName");

		if (infoVerifyGroupName != null) {
			setInfoVerifyGroupName(infoVerifyGroupName);
		}

		Date infoPolicyDate = (Date)attributes.get("infoPolicyDate");

		if (infoPolicyDate != null) {
			setInfoPolicyDate(infoPolicyDate);
		}

		Date infoPolicyDeployDate = (Date)attributes.get("infoPolicyDeployDate");

		if (infoPolicyDeployDate != null) {
			setInfoPolicyDeployDate(infoPolicyDeployDate);
		}
	}

	@Override
	public long getInvestPolicyId() {
		return _investPolicyId;
	}

	@Override
	public void setInvestPolicyId(long investPolicyId) {
		_investPolicyId = investPolicyId;
	}

	@Override
	public String getInfoPolicyTypeName() {
		if (_infoPolicyTypeName == null) {
			return StringPool.BLANK;
		}
		else {
			return _infoPolicyTypeName;
		}
	}

	@Override
	public void setInfoPolicyTypeName(String infoPolicyTypeName) {
		_infoPolicyTypeName = infoPolicyTypeName;
	}

	@Override
	public String getInfoPolicyName() {
		if (_infoPolicyName == null) {
			return StringPool.BLANK;
		}
		else {
			return _infoPolicyName;
		}
	}

	@Override
	public void setInfoPolicyName(String infoPolicyName) {
		_infoPolicyName = infoPolicyName;
	}

	@Override
	public String getInfoProposeGroupName() {
		if (_infoProposeGroupName == null) {
			return StringPool.BLANK;
		}
		else {
			return _infoProposeGroupName;
		}
	}

	@Override
	public void setInfoProposeGroupName(String infoProposeGroupName) {
		_infoProposeGroupName = infoProposeGroupName;
	}

	@Override
	public String getInfoVerifyGroupName() {
		if (_infoVerifyGroupName == null) {
			return StringPool.BLANK;
		}
		else {
			return _infoVerifyGroupName;
		}
	}

	@Override
	public void setInfoVerifyGroupName(String infoVerifyGroupName) {
		_infoVerifyGroupName = infoVerifyGroupName;
	}

	@Override
	public Date getInfoPolicyDate() {
		return _infoPolicyDate;
	}

	@Override
	public void setInfoPolicyDate(Date infoPolicyDate) {
		_infoPolicyDate = infoPolicyDate;
	}

	@Override
	public Date getInfoPolicyDeployDate() {
		return _infoPolicyDeployDate;
	}

	@Override
	public void setInfoPolicyDeployDate(Date infoPolicyDeployDate) {
		_infoPolicyDeployDate = infoPolicyDeployDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			VInvestPolicy.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VInvestPolicy toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VInvestPolicy)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VInvestPolicyImpl vInvestPolicyImpl = new VInvestPolicyImpl();

		vInvestPolicyImpl.setInvestPolicyId(getInvestPolicyId());
		vInvestPolicyImpl.setInfoPolicyTypeName(getInfoPolicyTypeName());
		vInvestPolicyImpl.setInfoPolicyName(getInfoPolicyName());
		vInvestPolicyImpl.setInfoProposeGroupName(getInfoProposeGroupName());
		vInvestPolicyImpl.setInfoVerifyGroupName(getInfoVerifyGroupName());
		vInvestPolicyImpl.setInfoPolicyDate(getInfoPolicyDate());
		vInvestPolicyImpl.setInfoPolicyDeployDate(getInfoPolicyDeployDate());

		vInvestPolicyImpl.resetOriginalValues();

		return vInvestPolicyImpl;
	}

	@Override
	public int compareTo(VInvestPolicy vInvestPolicy) {
		long primaryKey = vInvestPolicy.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VInvestPolicy)) {
			return false;
		}

		VInvestPolicy vInvestPolicy = (VInvestPolicy)obj;

		long primaryKey = vInvestPolicy.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<VInvestPolicy> toCacheModel() {
		VInvestPolicyCacheModel vInvestPolicyCacheModel = new VInvestPolicyCacheModel();

		vInvestPolicyCacheModel.investPolicyId = getInvestPolicyId();

		vInvestPolicyCacheModel.infoPolicyTypeName = getInfoPolicyTypeName();

		String infoPolicyTypeName = vInvestPolicyCacheModel.infoPolicyTypeName;

		if ((infoPolicyTypeName != null) && (infoPolicyTypeName.length() == 0)) {
			vInvestPolicyCacheModel.infoPolicyTypeName = null;
		}

		vInvestPolicyCacheModel.infoPolicyName = getInfoPolicyName();

		String infoPolicyName = vInvestPolicyCacheModel.infoPolicyName;

		if ((infoPolicyName != null) && (infoPolicyName.length() == 0)) {
			vInvestPolicyCacheModel.infoPolicyName = null;
		}

		vInvestPolicyCacheModel.infoProposeGroupName = getInfoProposeGroupName();

		String infoProposeGroupName = vInvestPolicyCacheModel.infoProposeGroupName;

		if ((infoProposeGroupName != null) &&
				(infoProposeGroupName.length() == 0)) {
			vInvestPolicyCacheModel.infoProposeGroupName = null;
		}

		vInvestPolicyCacheModel.infoVerifyGroupName = getInfoVerifyGroupName();

		String infoVerifyGroupName = vInvestPolicyCacheModel.infoVerifyGroupName;

		if ((infoVerifyGroupName != null) &&
				(infoVerifyGroupName.length() == 0)) {
			vInvestPolicyCacheModel.infoVerifyGroupName = null;
		}

		Date infoPolicyDate = getInfoPolicyDate();

		if (infoPolicyDate != null) {
			vInvestPolicyCacheModel.infoPolicyDate = infoPolicyDate.getTime();
		}
		else {
			vInvestPolicyCacheModel.infoPolicyDate = Long.MIN_VALUE;
		}

		Date infoPolicyDeployDate = getInfoPolicyDeployDate();

		if (infoPolicyDeployDate != null) {
			vInvestPolicyCacheModel.infoPolicyDeployDate = infoPolicyDeployDate.getTime();
		}
		else {
			vInvestPolicyCacheModel.infoPolicyDeployDate = Long.MIN_VALUE;
		}

		return vInvestPolicyCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{investPolicyId=");
		sb.append(getInvestPolicyId());
		sb.append(", infoPolicyTypeName=");
		sb.append(getInfoPolicyTypeName());
		sb.append(", infoPolicyName=");
		sb.append(getInfoPolicyName());
		sb.append(", infoProposeGroupName=");
		sb.append(getInfoProposeGroupName());
		sb.append(", infoVerifyGroupName=");
		sb.append(getInfoVerifyGroupName());
		sb.append(", infoPolicyDate=");
		sb.append(getInfoPolicyDate());
		sb.append(", infoPolicyDeployDate=");
		sb.append(getInfoPolicyDeployDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.viettel.ims.core.model.VInvestPolicy");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>investPolicyId</column-name><column-value><![CDATA[");
		sb.append(getInvestPolicyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoPolicyTypeName</column-name><column-value><![CDATA[");
		sb.append(getInfoPolicyTypeName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoPolicyName</column-name><column-value><![CDATA[");
		sb.append(getInfoPolicyName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoProposeGroupName</column-name><column-value><![CDATA[");
		sb.append(getInfoProposeGroupName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoVerifyGroupName</column-name><column-value><![CDATA[");
		sb.append(getInfoVerifyGroupName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoPolicyDate</column-name><column-value><![CDATA[");
		sb.append(getInfoPolicyDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>infoPolicyDeployDate</column-name><column-value><![CDATA[");
		sb.append(getInfoPolicyDeployDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = VInvestPolicy.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			VInvestPolicy.class
		};
	private long _investPolicyId;
	private String _infoPolicyTypeName;
	private String _infoPolicyName;
	private String _infoProposeGroupName;
	private String _infoVerifyGroupName;
	private Date _infoPolicyDate;
	private Date _infoPolicyDeployDate;
	private VInvestPolicy _escapedModel;
}