/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vnpt.portal.rss.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RssCategory service. Represents a row in the &quot;eportal_rss_category&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vnpt.portal.rss.model.impl.RssCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vnpt.portal.rss.model.impl.RssCategoryImpl}.
 * </p>
 *
 * @author MrNet
 * @see RssCategory
 * @see com.vnpt.portal.rss.model.impl.RssCategoryImpl
 * @see com.vnpt.portal.rss.model.impl.RssCategoryModelImpl
 * @generated
 */
public interface RssCategoryModel extends BaseModel<RssCategory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rss category model instance should use the {@link RssCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this rss category.
	 *
	 * @return the primary key of this rss category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rss category.
	 *
	 * @param primaryKey the primary key of this rss category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rss category ID of this rss category.
	 *
	 * @return the rss category ID of this rss category
	 */
	public long getRssCategoryId();

	/**
	 * Sets the rss category ID of this rss category.
	 *
	 * @param rssCategoryId the rss category ID of this rss category
	 */
	public void setRssCategoryId(long rssCategoryId);

	/**
	 * Returns the group ID of this rss category.
	 *
	 * @return the group ID of this rss category
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this rss category.
	 *
	 * @param groupId the group ID of this rss category
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this rss category.
	 *
	 * @return the company ID of this rss category
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this rss category.
	 *
	 * @param companyId the company ID of this rss category
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this rss category.
	 *
	 * @return the name of this rss category
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this rss category.
	 *
	 * @param name the name of this rss category
	 */
	public void setName(String name);

	/**
	 * Returns the description of this rss category.
	 *
	 * @return the description of this rss category
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this rss category.
	 *
	 * @param description the description of this rss category
	 */
	public void setDescription(String description);

	/**
	 * Returns the status of this rss category.
	 *
	 * @return the status of this rss category
	 */
	public int getStatus();

	/**
	 * Sets the status of this rss category.
	 *
	 * @param status the status of this rss category
	 */
	public void setStatus(int status);

	/**
	 * Returns the created ID of this rss category.
	 *
	 * @return the created ID of this rss category
	 */
	public long getCreatedId();

	/**
	 * Sets the created ID of this rss category.
	 *
	 * @param createdId the created ID of this rss category
	 */
	public void setCreatedId(long createdId);

	/**
	 * Returns the created date of this rss category.
	 *
	 * @return the created date of this rss category
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this rss category.
	 *
	 * @param createdDate the created date of this rss category
	 */
	public void setCreatedDate(Date createdDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.vnpt.portal.rss.model.RssCategory rssCategory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.vnpt.portal.rss.model.RssCategory> toCacheModel();

	@Override
	public com.vnpt.portal.rss.model.RssCategory toEscapedModel();

	@Override
	public com.vnpt.portal.rss.model.RssCategory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}