/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vnpt.portal.rss.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the RssConfig service. Represents a row in the &quot;eportal_rss_config&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vnpt.portal.rss.model.impl.RssConfigModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vnpt.portal.rss.model.impl.RssConfigImpl}.
 * </p>
 *
 * @author MrNet
 * @see RssConfig
 * @see com.vnpt.portal.rss.model.impl.RssConfigImpl
 * @see com.vnpt.portal.rss.model.impl.RssConfigModelImpl
 * @generated
 */
public interface RssConfigModel extends BaseModel<RssConfig> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rss config model instance should use the {@link RssConfig} interface instead.
	 */

	/**
	 * Returns the primary key of this rss config.
	 *
	 * @return the primary key of this rss config
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rss config.
	 *
	 * @param primaryKey the primary key of this rss config
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rss config ID of this rss config.
	 *
	 * @return the rss config ID of this rss config
	 */
	public long getRssConfigId();

	/**
	 * Sets the rss config ID of this rss config.
	 *
	 * @param rssConfigId the rss config ID of this rss config
	 */
	public void setRssConfigId(long rssConfigId);

	/**
	 * Returns the group ID of this rss config.
	 *
	 * @return the group ID of this rss config
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this rss config.
	 *
	 * @param groupId the group ID of this rss config
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this rss config.
	 *
	 * @return the company ID of this rss config
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this rss config.
	 *
	 * @param companyId the company ID of this rss config
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the title of this rss config.
	 *
	 * @return the title of this rss config
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this rss config.
	 *
	 * @param title the title of this rss config
	 */
	public void setTitle(String title);

	/**
	 * Returns the url of this rss config.
	 *
	 * @return the url of this rss config
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this rss config.
	 *
	 * @param url the url of this rss config
	 */
	public void setUrl(String url);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.vnpt.portal.rss.model.RssConfig rssConfig);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.vnpt.portal.rss.model.RssConfig> toCacheModel();

	@Override
	public com.vnpt.portal.rss.model.RssConfig toEscapedModel();

	@Override
	public com.vnpt.portal.rss.model.RssConfig toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}