/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vnpt.portal.rss.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.vnpt.portal.rss.model.RssConfig;
import com.vnpt.portal.rss.service.RssConfigLocalServiceUtil;

/**
 * The extended model base implementation for the RssConfig service. Represents a row in the &quot;eportal_rss_config&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RssConfigImpl}.
 * </p>
 *
 * @author MrNet
 * @see RssConfigImpl
 * @see com.vnpt.portal.rss.model.RssConfig
 * @generated
 */
public abstract class RssConfigBaseImpl extends RssConfigModelImpl
	implements RssConfig {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rss config model instance should use the {@link RssConfig} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			RssConfigLocalServiceUtil.addRssConfig(this);
		}
		else {
			RssConfigLocalServiceUtil.updateRssConfig(this);
		}
	}
}