/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.viettel.ims.core.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the InvestCategories service. Represents a row in the &quot;Invest_Categories&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.ims.core.model.impl.InvestCategoriesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.ims.core.model.impl.InvestCategoriesImpl}.
 * </p>
 *
 * @author MrNet
 * @see InvestCategories
 * @see com.viettel.ims.core.model.impl.InvestCategoriesImpl
 * @see com.viettel.ims.core.model.impl.InvestCategoriesModelImpl
 * @generated
 */
public interface InvestCategoriesModel extends BaseModel<InvestCategories> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a invest categories model instance should use the {@link InvestCategories} interface instead.
	 */

	/**
	 * Returns the primary key of this invest categories.
	 *
	 * @return the primary key of this invest categories
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this invest categories.
	 *
	 * @param primaryKey the primary key of this invest categories
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the invest categories ID of this invest categories.
	 *
	 * @return the invest categories ID of this invest categories
	 */
	public long getInvestCategoriesId();

	/**
	 * Sets the invest categories ID of this invest categories.
	 *
	 * @param investCategoriesId the invest categories ID of this invest categories
	 */
	public void setInvestCategoriesId(long investCategoriesId);

	/**
	 * Returns the obj ID of this invest categories.
	 *
	 * @return the obj ID of this invest categories
	 */
	public long getObjId();

	/**
	 * Sets the obj ID of this invest categories.
	 *
	 * @param objId the obj ID of this invest categories
	 */
	public void setObjId(long objId);

	/**
	 * Returns the name of this invest categories.
	 *
	 * @return the name of this invest categories
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this invest categories.
	 *
	 * @param name the name of this invest categories
	 */
	public void setName(String name);

	/**
	 * Returns the description of this invest categories.
	 *
	 * @return the description of this invest categories
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this invest categories.
	 *
	 * @param description the description of this invest categories
	 */
	public void setDescription(String description);

	/**
	 * Returns the unit ID of this invest categories.
	 *
	 * @return the unit ID of this invest categories
	 */
	public long getUnitId();

	/**
	 * Sets the unit ID of this invest categories.
	 *
	 * @param unitId the unit ID of this invest categories
	 */
	public void setUnitId(long unitId);

	/**
	 * Returns the cost type of this invest categories.
	 *
	 * @return the cost type of this invest categories
	 */
	public long getCostType();

	/**
	 * Sets the cost type of this invest categories.
	 *
	 * @param costType the cost type of this invest categories
	 */
	public void setCostType(long costType);

	/**
	 * Returns the quantity of this invest categories.
	 *
	 * @return the quantity of this invest categories
	 */
	public double getQuantity();

	/**
	 * Sets the quantity of this invest categories.
	 *
	 * @param quantity the quantity of this invest categories
	 */
	public void setQuantity(double quantity);

	/**
	 * Returns the used quantity of this invest categories.
	 *
	 * @return the used quantity of this invest categories
	 */
	public double getUsedQuantity();

	/**
	 * Sets the used quantity of this invest categories.
	 *
	 * @param usedQuantity the used quantity of this invest categories
	 */
	public void setUsedQuantity(double usedQuantity);

	/**
	 * Returns the unit price of this invest categories.
	 *
	 * @return the unit price of this invest categories
	 */
	public double getUnitPrice();

	/**
	 * Sets the unit price of this invest categories.
	 *
	 * @param unitPrice the unit price of this invest categories
	 */
	public void setUnitPrice(double unitPrice);

	/**
	 * Returns the cat currency ID of this invest categories.
	 *
	 * @return the cat currency ID of this invest categories
	 */
	public long getCatCurrencyId();

	/**
	 * Sets the cat currency ID of this invest categories.
	 *
	 * @param catCurrencyId the cat currency ID of this invest categories
	 */
	public void setCatCurrencyId(long catCurrencyId);

	/**
	 * Returns the type of this invest categories.
	 *
	 * @return the type of this invest categories
	 */
	public long getType();

	/**
	 * Sets the type of this invest categories.
	 *
	 * @param type the type of this invest categories
	 */
	public void setType(long type);

	/**
	 * Returns the vat of this invest categories.
	 *
	 * @return the vat of this invest categories
	 */
	public double getVat();

	/**
	 * Sets the vat of this invest categories.
	 *
	 * @param vat the vat of this invest categories
	 */
	public void setVat(double vat);

	/**
	 * Returns the is active of this invest categories.
	 *
	 * @return the is active of this invest categories
	 */
	public long getIsActive();

	/**
	 * Sets the is active of this invest categories.
	 *
	 * @param isActive the is active of this invest categories
	 */
	public void setIsActive(long isActive);

	/**
	 * Returns the created ID of this invest categories.
	 *
	 * @return the created ID of this invest categories
	 */
	public long getCreatedId();

	/**
	 * Sets the created ID of this invest categories.
	 *
	 * @param createdId the created ID of this invest categories
	 */
	public void setCreatedId(long createdId);

	/**
	 * Returns the created date of this invest categories.
	 *
	 * @return the created date of this invest categories
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this invest categories.
	 *
	 * @param createdDate the created date of this invest categories
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modifield ID of this invest categories.
	 *
	 * @return the modifield ID of this invest categories
	 */
	public long getModifieldId();

	/**
	 * Sets the modifield ID of this invest categories.
	 *
	 * @param modifieldId the modifield ID of this invest categories
	 */
	public void setModifieldId(long modifieldId);

	/**
	 * Returns the modifield date of this invest categories.
	 *
	 * @return the modifield date of this invest categories
	 */
	public Date getModifieldDate();

	/**
	 * Sets the modifield date of this invest categories.
	 *
	 * @param modifieldDate the modifield date of this invest categories
	 */
	public void setModifieldDate(Date modifieldDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.viettel.ims.core.model.InvestCategories investCategories);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.ims.core.model.InvestCategories> toCacheModel();

	@Override
	public com.viettel.ims.core.model.InvestCategories toEscapedModel();

	@Override
	public com.viettel.ims.core.model.InvestCategories toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}