/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.viettel.ams.core.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AssetManageReqHandleEntity service. Represents a row in the &quot;Asset_Manage_Req_Handle_Entity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.ams.core.model.impl.AssetManageReqHandleEntityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.ams.core.model.impl.AssetManageReqHandleEntityImpl}.
 * </p>
 *
 * @author MrNet
 * @see AssetManageReqHandleEntity
 * @see com.viettel.ams.core.model.impl.AssetManageReqHandleEntityImpl
 * @see com.viettel.ams.core.model.impl.AssetManageReqHandleEntityModelImpl
 * @generated
 */
public interface AssetManageReqHandleEntityModel extends BaseModel<AssetManageReqHandleEntity> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset manage req handle entity model instance should use the {@link AssetManageReqHandleEntity} interface instead.
	 */

	/**
	 * Returns the primary key of this asset manage req handle entity.
	 *
	 * @return the primary key of this asset manage req handle entity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset manage req handle entity.
	 *
	 * @param primaryKey the primary key of this asset manage req handle entity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this asset manage req handle entity.
	 *
	 * @return the ID of this asset manage req handle entity
	 */
	public long getId();

	/**
	 * Sets the ID of this asset manage req handle entity.
	 *
	 * @param id the ID of this asset manage req handle entity
	 */
	public void setId(long id);

	/**
	 * Returns the handle ID of this asset manage req handle entity.
	 *
	 * @return the handle ID of this asset manage req handle entity
	 */
	public Long getHandleId();

	/**
	 * Sets the handle ID of this asset manage req handle entity.
	 *
	 * @param handleId the handle ID of this asset manage req handle entity
	 */
	public void setHandleId(Long handleId);

	/**
	 * Returns the mer entity ID of this asset manage req handle entity.
	 *
	 * @return the mer entity ID of this asset manage req handle entity
	 */
	public Long getMerEntityId();

	/**
	 * Sets the mer entity ID of this asset manage req handle entity.
	 *
	 * @param merEntityId the mer entity ID of this asset manage req handle entity
	 */
	public void setMerEntityId(Long merEntityId);

	/**
	 * Returns the status of this asset manage req handle entity.
	 *
	 * @return the status of this asset manage req handle entity
	 */
	public Long getStatus();

	/**
	 * Sets the status of this asset manage req handle entity.
	 *
	 * @param status the status of this asset manage req handle entity
	 */
	public void setStatus(Long status);

	/**
	 * Returns the station ID of this asset manage req handle entity.
	 *
	 * @return the station ID of this asset manage req handle entity
	 */
	public Long getStationId();

	/**
	 * Sets the station ID of this asset manage req handle entity.
	 *
	 * @param stationId the station ID of this asset manage req handle entity
	 */
	public void setStationId(Long stationId);

	/**
	 * Returns the fail date of this asset manage req handle entity.
	 *
	 * @return the fail date of this asset manage req handle entity
	 */
	public Date getFailDate();

	/**
	 * Sets the fail date of this asset manage req handle entity.
	 *
	 * @param failDate the fail date of this asset manage req handle entity
	 */
	public void setFailDate(Date failDate);

	/**
	 * Returns the fail reason of this asset manage req handle entity.
	 *
	 * @return the fail reason of this asset manage req handle entity
	 */
	@AutoEscape
	public String getFailReason();

	/**
	 * Sets the fail reason of this asset manage req handle entity.
	 *
	 * @param failReason the fail reason of this asset manage req handle entity
	 */
	public void setFailReason(String failReason);

	/**
	 * Returns the used date of this asset manage req handle entity.
	 *
	 * @return the used date of this asset manage req handle entity
	 */
	public Date getUsedDate();

	/**
	 * Sets the used date of this asset manage req handle entity.
	 *
	 * @param usedDate the used date of this asset manage req handle entity
	 */
	public void setUsedDate(Date usedDate);

	/**
	 * Returns the hand over ID of this asset manage req handle entity.
	 *
	 * @return the hand over ID of this asset manage req handle entity
	 */
	public Long getHandOverId();

	/**
	 * Sets the hand over ID of this asset manage req handle entity.
	 *
	 * @param handOverId the hand over ID of this asset manage req handle entity
	 */
	public void setHandOverId(Long handOverId);

	/**
	 * Returns the quantity of this asset manage req handle entity.
	 *
	 * @return the quantity of this asset manage req handle entity
	 */
	public Double getQuantity();

	/**
	 * Sets the quantity of this asset manage req handle entity.
	 *
	 * @param quantity the quantity of this asset manage req handle entity
	 */
	public void setQuantity(Double quantity);

	/**
	 * Returns the unit price of this asset manage req handle entity.
	 *
	 * @return the unit price of this asset manage req handle entity
	 */
	public Double getUnitPrice();

	/**
	 * Sets the unit price of this asset manage req handle entity.
	 *
	 * @param unitPrice the unit price of this asset manage req handle entity
	 */
	public void setUnitPrice(Double unitPrice);

	/**
	 * Returns the description of this asset manage req handle entity.
	 *
	 * @return the description of this asset manage req handle entity
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this asset manage req handle entity.
	 *
	 * @param description the description of this asset manage req handle entity
	 */
	public void setDescription(String description);

	/**
	 * Returns the upgrade parent ID of this asset manage req handle entity.
	 *
	 * @return the upgrade parent ID of this asset manage req handle entity
	 */
	public Long getUpgradeParentId();

	/**
	 * Sets the upgrade parent ID of this asset manage req handle entity.
	 *
	 * @param upgradeParentId the upgrade parent ID of this asset manage req handle entity
	 */
	public void setUpgradeParentId(Long upgradeParentId);

	/**
	 * Returns the parent ID of this asset manage req handle entity.
	 *
	 * @return the parent ID of this asset manage req handle entity
	 */
	public Long getParentId();

	/**
	 * Sets the parent ID of this asset manage req handle entity.
	 *
	 * @param parentId the parent ID of this asset manage req handle entity
	 */
	public void setParentId(Long parentId);

	/**
	 * Returns the group ID of this asset manage req handle entity.
	 *
	 * @return the group ID of this asset manage req handle entity
	 */
	public Long getGroupId();

	/**
	 * Sets the group ID of this asset manage req handle entity.
	 *
	 * @param groupId the group ID of this asset manage req handle entity
	 */
	public void setGroupId(Long groupId);

	/**
	 * Returns the time retrieve of this asset manage req handle entity.
	 *
	 * @return the time retrieve of this asset manage req handle entity
	 */
	public Date getTimeRetrieve();

	/**
	 * Sets the time retrieve of this asset manage req handle entity.
	 *
	 * @param timeRetrieve the time retrieve of this asset manage req handle entity
	 */
	public void setTimeRetrieve(Date timeRetrieve);

	/**
	 * Returns the status ID of this asset manage req handle entity.
	 *
	 * @return the status ID of this asset manage req handle entity
	 */
	public Long getStatusId();

	/**
	 * Sets the status ID of this asset manage req handle entity.
	 *
	 * @param statusId the status ID of this asset manage req handle entity
	 */
	public void setStatusId(Long statusId);

	/**
	 * Returns the mark of this asset manage req handle entity.
	 *
	 * @return the mark of this asset manage req handle entity
	 */
	public Long getMark();

	/**
	 * Sets the mark of this asset manage req handle entity.
	 *
	 * @param mark the mark of this asset manage req handle entity
	 */
	public void setMark(Long mark);

	/**
	 * Returns the old status ID of this asset manage req handle entity.
	 *
	 * @return the old status ID of this asset manage req handle entity
	 */
	public Long getOldStatusId();

	/**
	 * Sets the old status ID of this asset manage req handle entity.
	 *
	 * @param oldStatusId the old status ID of this asset manage req handle entity
	 */
	public void setOldStatusId(Long oldStatusId);

	/**
	 * Returns the pre cat employee ID of this asset manage req handle entity.
	 *
	 * @return the pre cat employee ID of this asset manage req handle entity
	 */
	public Long getPreCatEmployeeId();

	/**
	 * Sets the pre cat employee ID of this asset manage req handle entity.
	 *
	 * @param preCatEmployeeId the pre cat employee ID of this asset manage req handle entity
	 */
	public void setPreCatEmployeeId(Long preCatEmployeeId);

	/**
	 * Returns the percent quality of this asset manage req handle entity.
	 *
	 * @return the percent quality of this asset manage req handle entity
	 */
	public Long getPercentQuality();

	/**
	 * Sets the percent quality of this asset manage req handle entity.
	 *
	 * @param percentQuality the percent quality of this asset manage req handle entity
	 */
	public void setPercentQuality(Long percentQuality);

	/**
	 * Returns the withdraw price of this asset manage req handle entity.
	 *
	 * @return the withdraw price of this asset manage req handle entity
	 */
	public Long getWithdrawPrice();

	/**
	 * Sets the withdraw price of this asset manage req handle entity.
	 *
	 * @param withdrawPrice the withdraw price of this asset manage req handle entity
	 */
	public void setWithdrawPrice(Long withdrawPrice);

	/**
	 * Returns the delivery note ID of this asset manage req handle entity.
	 *
	 * @return the delivery note ID of this asset manage req handle entity
	 */
	public Long getDeliveryNoteId();

	/**
	 * Sets the delivery note ID of this asset manage req handle entity.
	 *
	 * @param deliveryNoteId the delivery note ID of this asset manage req handle entity
	 */
	public void setDeliveryNoteId(Long deliveryNoteId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.viettel.ams.core.model.AssetManageReqHandleEntity assetManageReqHandleEntity);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.ams.core.model.AssetManageReqHandleEntity> toCacheModel();

	@Override
	public com.viettel.ams.core.model.AssetManageReqHandleEntity toEscapedModel();

	@Override
	public com.viettel.ams.core.model.AssetManageReqHandleEntity toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}