/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.viettel.ams.core.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AssetManageReqHandle service. Represents a row in the &quot;Asset_Manage_Req_Handle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.ams.core.model.impl.AssetManageReqHandleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.ams.core.model.impl.AssetManageReqHandleImpl}.
 * </p>
 *
 * @author MrNet
 * @see AssetManageReqHandle
 * @see com.viettel.ams.core.model.impl.AssetManageReqHandleImpl
 * @see com.viettel.ams.core.model.impl.AssetManageReqHandleModelImpl
 * @generated
 */
public interface AssetManageReqHandleModel extends BaseModel<AssetManageReqHandle> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset manage req handle model instance should use the {@link AssetManageReqHandle} interface instead.
	 */

	/**
	 * Returns the primary key of this asset manage req handle.
	 *
	 * @return the primary key of this asset manage req handle
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset manage req handle.
	 *
	 * @param primaryKey the primary key of this asset manage req handle
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the handle ID of this asset manage req handle.
	 *
	 * @return the handle ID of this asset manage req handle
	 */
	public long getHandleId();

	/**
	 * Sets the handle ID of this asset manage req handle.
	 *
	 * @param handleId the handle ID of this asset manage req handle
	 */
	public void setHandleId(long handleId);

	/**
	 * Returns the manage req ID of this asset manage req handle.
	 *
	 * @return the manage req ID of this asset manage req handle
	 */
	public Long getManageReqId();

	/**
	 * Sets the manage req ID of this asset manage req handle.
	 *
	 * @param manageReqId the manage req ID of this asset manage req handle
	 */
	public void setManageReqId(Long manageReqId);

	/**
	 * Returns the description of this asset manage req handle.
	 *
	 * @return the description of this asset manage req handle
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this asset manage req handle.
	 *
	 * @param description the description of this asset manage req handle
	 */
	public void setDescription(String description);

	/**
	 * Returns the updator ID of this asset manage req handle.
	 *
	 * @return the updator ID of this asset manage req handle
	 */
	public Long getUpdatorId();

	/**
	 * Sets the updator ID of this asset manage req handle.
	 *
	 * @param updatorId the updator ID of this asset manage req handle
	 */
	public void setUpdatorId(Long updatorId);

	/**
	 * Returns the update date of this asset manage req handle.
	 *
	 * @return the update date of this asset manage req handle
	 */
	public Date getUpdateDate();

	/**
	 * Sets the update date of this asset manage req handle.
	 *
	 * @param updateDate the update date of this asset manage req handle
	 */
	public void setUpdateDate(Date updateDate);

	/**
	 * Returns the status of this asset manage req handle.
	 *
	 * @return the status of this asset manage req handle
	 */
	public Long getStatus();

	/**
	 * Sets the status of this asset manage req handle.
	 *
	 * @param status the status of this asset manage req handle
	 */
	public void setStatus(Long status);

	/**
	 * Returns the code of this asset manage req handle.
	 *
	 * @return the code of this asset manage req handle
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this asset manage req handle.
	 *
	 * @param code the code of this asset manage req handle
	 */
	public void setCode(String code);

	/**
	 * Returns the create group ID of this asset manage req handle.
	 *
	 * @return the create group ID of this asset manage req handle
	 */
	public Long getCreateGroupId();

	/**
	 * Sets the create group ID of this asset manage req handle.
	 *
	 * @param createGroupId the create group ID of this asset manage req handle
	 */
	public void setCreateGroupId(Long createGroupId);

	/**
	 * Returns the imp req ID of this asset manage req handle.
	 *
	 * @return the imp req ID of this asset manage req handle
	 */
	public Long getImpReqId();

	/**
	 * Sets the imp req ID of this asset manage req handle.
	 *
	 * @param impReqId the imp req ID of this asset manage req handle
	 */
	public void setImpReqId(Long impReqId);

	/**
	 * Returns the req delegator of this asset manage req handle.
	 *
	 * @return the req delegator of this asset manage req handle
	 */
	@AutoEscape
	public String getReqDelegator();

	/**
	 * Sets the req delegator of this asset manage req handle.
	 *
	 * @param reqDelegator the req delegator of this asset manage req handle
	 */
	public void setReqDelegator(String reqDelegator);

	/**
	 * Returns the req delegator position of this asset manage req handle.
	 *
	 * @return the req delegator position of this asset manage req handle
	 */
	@AutoEscape
	public String getReqDelegatorPosition();

	/**
	 * Sets the req delegator position of this asset manage req handle.
	 *
	 * @param reqDelegatorPosition the req delegator position of this asset manage req handle
	 */
	public void setReqDelegatorPosition(String reqDelegatorPosition);

	/**
	 * Returns the document of this asset manage req handle.
	 *
	 * @return the document of this asset manage req handle
	 */
	@AutoEscape
	public String getDocument();

	/**
	 * Sets the document of this asset manage req handle.
	 *
	 * @param document the document of this asset manage req handle
	 */
	public void setDocument(String document);

	/**
	 * Returns the begin date of this asset manage req handle.
	 *
	 * @return the begin date of this asset manage req handle
	 */
	public Date getBeginDate();

	/**
	 * Sets the begin date of this asset manage req handle.
	 *
	 * @param beginDate the begin date of this asset manage req handle
	 */
	public void setBeginDate(Date beginDate);

	/**
	 * Returns the end date of this asset manage req handle.
	 *
	 * @return the end date of this asset manage req handle
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this asset manage req handle.
	 *
	 * @param endDate the end date of this asset manage req handle
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the kcs code of this asset manage req handle.
	 *
	 * @return the kcs code of this asset manage req handle
	 */
	@AutoEscape
	public String getKcsCode();

	/**
	 * Sets the kcs code of this asset manage req handle.
	 *
	 * @param kcsCode the kcs code of this asset manage req handle
	 */
	public void setKcsCode(String kcsCode);

	/**
	 * Returns the hand over ID of this asset manage req handle.
	 *
	 * @return the hand over ID of this asset manage req handle
	 */
	public Long getHandOverId();

	/**
	 * Sets the hand over ID of this asset manage req handle.
	 *
	 * @param handOverId the hand over ID of this asset manage req handle
	 */
	public void setHandOverId(Long handOverId);

	/**
	 * Returns the imp req code of this asset manage req handle.
	 *
	 * @return the imp req code of this asset manage req handle
	 */
	@AutoEscape
	public String getImpReqCode();

	/**
	 * Sets the imp req code of this asset manage req handle.
	 *
	 * @param impReqCode the imp req code of this asset manage req handle
	 */
	public void setImpReqCode(String impReqCode);

	/**
	 * Returns the base kcs code of this asset manage req handle.
	 *
	 * @return the base kcs code of this asset manage req handle
	 */
	public Long getBaseKcsCode();

	/**
	 * Sets the base kcs code of this asset manage req handle.
	 *
	 * @param baseKcsCode the base kcs code of this asset manage req handle
	 */
	public void setBaseKcsCode(Long baseKcsCode);

	/**
	 * Returns the creator kcs of this asset manage req handle.
	 *
	 * @return the creator kcs of this asset manage req handle
	 */
	public Long getCreatorKcs();

	/**
	 * Sets the creator kcs of this asset manage req handle.
	 *
	 * @param creatorKcs the creator kcs of this asset manage req handle
	 */
	public void setCreatorKcs(Long creatorKcs);

	/**
	 * Returns the asset type of this asset manage req handle.
	 *
	 * @return the asset type of this asset manage req handle
	 */
	public Long getAssetType();

	/**
	 * Sets the asset type of this asset manage req handle.
	 *
	 * @param assetType the asset type of this asset manage req handle
	 */
	public void setAssetType(Long assetType);

	/**
	 * Returns the is not modify of this asset manage req handle.
	 *
	 * @return the is not modify of this asset manage req handle
	 */
	public Long getIsNotModify();

	/**
	 * Sets the is not modify of this asset manage req handle.
	 *
	 * @param isNotModify the is not modify of this asset manage req handle
	 */
	public void setIsNotModify(Long isNotModify);

	/**
	 * Returns the handle delegator of this asset manage req handle.
	 *
	 * @return the handle delegator of this asset manage req handle
	 */
	@AutoEscape
	public String getHandleDelegator();

	/**
	 * Sets the handle delegator of this asset manage req handle.
	 *
	 * @param handleDelegator the handle delegator of this asset manage req handle
	 */
	public void setHandleDelegator(String handleDelegator);

	/**
	 * Returns the handle delegator position of this asset manage req handle.
	 *
	 * @return the handle delegator position of this asset manage req handle
	 */
	@AutoEscape
	public String getHandleDelegatorPosition();

	/**
	 * Sets the handle delegator position of this asset manage req handle.
	 *
	 * @param handleDelegatorPosition the handle delegator position of this asset manage req handle
	 */
	public void setHandleDelegatorPosition(String handleDelegatorPosition);

	/**
	 * Returns the contract ID of this asset manage req handle.
	 *
	 * @return the contract ID of this asset manage req handle
	 */
	public Long getContractId();

	/**
	 * Sets the contract ID of this asset manage req handle.
	 *
	 * @param contractId the contract ID of this asset manage req handle
	 */
	public void setContractId(Long contractId);

	/**
	 * Returns the status ca of this asset manage req handle.
	 *
	 * @return the status ca of this asset manage req handle
	 */
	public Long getStatusCa();

	/**
	 * Sets the status ca of this asset manage req handle.
	 *
	 * @param statusCa the status ca of this asset manage req handle
	 */
	public void setStatusCa(Long statusCa);

	/**
	 * Returns the comment ca of this asset manage req handle.
	 *
	 * @return the comment ca of this asset manage req handle
	 */
	@AutoEscape
	public String getCommentCa();

	/**
	 * Sets the comment ca of this asset manage req handle.
	 *
	 * @param commentCa the comment ca of this asset manage req handle
	 */
	public void setCommentCa(String commentCa);

	/**
	 * Returns the document ca ID of this asset manage req handle.
	 *
	 * @return the document ca ID of this asset manage req handle
	 */
	public Long getDocumentCaId();

	/**
	 * Sets the document ca ID of this asset manage req handle.
	 *
	 * @param documentCaId the document ca ID of this asset manage req handle
	 */
	public void setDocumentCaId(Long documentCaId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.viettel.ams.core.model.AssetManageReqHandle assetManageReqHandle);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.ams.core.model.AssetManageReqHandle> toCacheModel();

	@Override
	public com.viettel.ams.core.model.AssetManageReqHandle toEscapedModel();

	@Override
	public com.viettel.ams.core.model.AssetManageReqHandle toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}