/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.viettel.ams.core.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AssetManageReq service. Represents a row in the &quot;Asset_Manage_Req&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.ams.core.model.impl.AssetManageReqModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.ams.core.model.impl.AssetManageReqImpl}.
 * </p>
 *
 * @author MrNet
 * @see AssetManageReq
 * @see com.viettel.ams.core.model.impl.AssetManageReqImpl
 * @see com.viettel.ams.core.model.impl.AssetManageReqModelImpl
 * @generated
 */
public interface AssetManageReqModel extends BaseModel<AssetManageReq> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset manage req model instance should use the {@link AssetManageReq} interface instead.
	 */

	/**
	 * Returns the primary key of this asset manage req.
	 *
	 * @return the primary key of this asset manage req
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset manage req.
	 *
	 * @param primaryKey the primary key of this asset manage req
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the manage req ID of this asset manage req.
	 *
	 * @return the manage req ID of this asset manage req
	 */
	public long getManageReqId();

	/**
	 * Sets the manage req ID of this asset manage req.
	 *
	 * @param manageReqId the manage req ID of this asset manage req
	 */
	public void setManageReqId(long manageReqId);

	/**
	 * Returns the req group ID of this asset manage req.
	 *
	 * @return the req group ID of this asset manage req
	 */
	public Long getReqGroupId();

	/**
	 * Sets the req group ID of this asset manage req.
	 *
	 * @param reqGroupId the req group ID of this asset manage req
	 */
	public void setReqGroupId(Long reqGroupId);

	/**
	 * Returns the user ID of this asset manage req.
	 *
	 * @return the user ID of this asset manage req
	 */
	public Long getUserId();

	/**
	 * Sets the user ID of this asset manage req.
	 *
	 * @param userId the user ID of this asset manage req
	 */
	public void setUserId(Long userId);

	/**
	 * Returns the recv group ID of this asset manage req.
	 *
	 * @return the recv group ID of this asset manage req
	 */
	public Long getRecvGroupId();

	/**
	 * Sets the recv group ID of this asset manage req.
	 *
	 * @param recvGroupId the recv group ID of this asset manage req
	 */
	public void setRecvGroupId(Long recvGroupId);

	/**
	 * Returns the cause of this asset manage req.
	 *
	 * @return the cause of this asset manage req
	 */
	@AutoEscape
	public String getCause();

	/**
	 * Sets the cause of this asset manage req.
	 *
	 * @param cause the cause of this asset manage req
	 */
	public void setCause(String cause);

	/**
	 * Returns the creator ID of this asset manage req.
	 *
	 * @return the creator ID of this asset manage req
	 */
	public Long getCreatorId();

	/**
	 * Sets the creator ID of this asset manage req.
	 *
	 * @param creatorId the creator ID of this asset manage req
	 */
	public void setCreatorId(Long creatorId);

	/**
	 * Returns the created date of this asset manage req.
	 *
	 * @return the created date of this asset manage req
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this asset manage req.
	 *
	 * @param createdDate the created date of this asset manage req
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the status of this asset manage req.
	 *
	 * @return the status of this asset manage req
	 */
	public Long getStatus();

	/**
	 * Sets the status of this asset manage req.
	 *
	 * @param status the status of this asset manage req
	 */
	public void setStatus(Long status);

	/**
	 * Returns the type of this asset manage req.
	 *
	 * @return the type of this asset manage req
	 */
	public Long getType();

	/**
	 * Sets the type of this asset manage req.
	 *
	 * @param type the type of this asset manage req
	 */
	public void setType(Long type);

	/**
	 * Returns the used group ID of this asset manage req.
	 *
	 * @return the used group ID of this asset manage req
	 */
	public Long getUsedGroupId();

	/**
	 * Sets the used group ID of this asset manage req.
	 *
	 * @param usedGroupId the used group ID of this asset manage req
	 */
	public void setUsedGroupId(Long usedGroupId);

	/**
	 * Returns the code of this asset manage req.
	 *
	 * @return the code of this asset manage req
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this asset manage req.
	 *
	 * @param code the code of this asset manage req
	 */
	public void setCode(String code);

	/**
	 * Returns the acceptor ID of this asset manage req.
	 *
	 * @return the acceptor ID of this asset manage req
	 */
	public Long getAcceptorId();

	/**
	 * Sets the acceptor ID of this asset manage req.
	 *
	 * @param acceptorId the acceptor ID of this asset manage req
	 */
	public void setAcceptorId(Long acceptorId);

	/**
	 * Returns the accept comment of this asset manage req.
	 *
	 * @return the accept comment of this asset manage req
	 */
	@AutoEscape
	public String getAcceptComment();

	/**
	 * Sets the accept comment of this asset manage req.
	 *
	 * @param acceptComment the accept comment of this asset manage req
	 */
	public void setAcceptComment(String acceptComment);

	/**
	 * Returns the retrieve cause ID of this asset manage req.
	 *
	 * @return the retrieve cause ID of this asset manage req
	 */
	public Long getRetrieveCauseId();

	/**
	 * Sets the retrieve cause ID of this asset manage req.
	 *
	 * @param retrieveCauseId the retrieve cause ID of this asset manage req
	 */
	public void setRetrieveCauseId(Long retrieveCauseId);

	/**
	 * Returns the construct ID of this asset manage req.
	 *
	 * @return the construct ID of this asset manage req
	 */
	public Long getConstructId();

	/**
	 * Sets the construct ID of this asset manage req.
	 *
	 * @param constructId the construct ID of this asset manage req
	 */
	public void setConstructId(Long constructId);

	/**
	 * Returns the delegator of this asset manage req.
	 *
	 * @return the delegator of this asset manage req
	 */
	@AutoEscape
	public String getDelegator();

	/**
	 * Sets the delegator of this asset manage req.
	 *
	 * @param delegator the delegator of this asset manage req
	 */
	public void setDelegator(String delegator);

	/**
	 * Returns the is full of this asset manage req.
	 *
	 * @return the is full of this asset manage req
	 */
	public Long getIsFull();

	/**
	 * Sets the is full of this asset manage req.
	 *
	 * @param isFull the is full of this asset manage req
	 */
	public void setIsFull(Long isFull);

	/**
	 * Returns the title delegator of this asset manage req.
	 *
	 * @return the title delegator of this asset manage req
	 */
	@AutoEscape
	public String getTitleDelegator();

	/**
	 * Sets the title delegator of this asset manage req.
	 *
	 * @param titleDelegator the title delegator of this asset manage req
	 */
	public void setTitleDelegator(String titleDelegator);

	/**
	 * Returns the mobile number of this asset manage req.
	 *
	 * @return the mobile number of this asset manage req
	 */
	public Long getMobileNumber();

	/**
	 * Sets the mobile number of this asset manage req.
	 *
	 * @param mobileNumber the mobile number of this asset manage req
	 */
	public void setMobileNumber(Long mobileNumber);

	/**
	 * Returns the document of this asset manage req.
	 *
	 * @return the document of this asset manage req
	 */
	@AutoEscape
	public String getDocument();

	/**
	 * Sets the document of this asset manage req.
	 *
	 * @param document the document of this asset manage req
	 */
	public void setDocument(String document);

	/**
	 * Returns the fail check ID of this asset manage req.
	 *
	 * @return the fail check ID of this asset manage req
	 */
	public Long getFailCheckId();

	/**
	 * Sets the fail check ID of this asset manage req.
	 *
	 * @param failCheckId the fail check ID of this asset manage req
	 */
	public void setFailCheckId(Long failCheckId);

	/**
	 * Returns the delivery note ID of this asset manage req.
	 *
	 * @return the delivery note ID of this asset manage req
	 */
	public Long getDeliveryNoteId();

	/**
	 * Sets the delivery note ID of this asset manage req.
	 *
	 * @param deliveryNoteId the delivery note ID of this asset manage req
	 */
	public void setDeliveryNoteId(Long deliveryNoteId);

	/**
	 * Returns the is maintain of this asset manage req.
	 *
	 * @return the is maintain of this asset manage req
	 */
	public Long getIsMaintain();

	/**
	 * Sets the is maintain of this asset manage req.
	 *
	 * @param isMaintain the is maintain of this asset manage req
	 */
	public void setIsMaintain(Long isMaintain);

	/**
	 * Returns the cause reject of this asset manage req.
	 *
	 * @return the cause reject of this asset manage req
	 */
	@AutoEscape
	public String getCauseReject();

	/**
	 * Sets the cause reject of this asset manage req.
	 *
	 * @param causeReject the cause reject of this asset manage req
	 */
	public void setCauseReject(String causeReject);

	/**
	 * Returns the asset type of this asset manage req.
	 *
	 * @return the asset type of this asset manage req
	 */
	public Long getAssetType();

	/**
	 * Sets the asset type of this asset manage req.
	 *
	 * @param assetType the asset type of this asset manage req
	 */
	public void setAssetType(Long assetType);

	/**
	 * Returns the retrieve type of this asset manage req.
	 *
	 * @return the retrieve type of this asset manage req
	 */
	public Long getRetrieveType();

	/**
	 * Sets the retrieve type of this asset manage req.
	 *
	 * @param retrieveType the retrieve type of this asset manage req
	 */
	public void setRetrieveType(Long retrieveType);

	/**
	 * Returns the retrieve cmd ID of this asset manage req.
	 *
	 * @return the retrieve cmd ID of this asset manage req
	 */
	public Long getRetrieveCmdId();

	/**
	 * Sets the retrieve cmd ID of this asset manage req.
	 *
	 * @param retrieveCmdId the retrieve cmd ID of this asset manage req
	 */
	public void setRetrieveCmdId(Long retrieveCmdId);

	/**
	 * Returns the plan swap ID of this asset manage req.
	 *
	 * @return the plan swap ID of this asset manage req
	 */
	public Long getPlanSwapId();

	/**
	 * Sets the plan swap ID of this asset manage req.
	 *
	 * @param planSwapId the plan swap ID of this asset manage req
	 */
	public void setPlanSwapId(Long planSwapId);

	/**
	 * Returns the certificate registration ID of this asset manage req.
	 *
	 * @return the certificate registration ID of this asset manage req
	 */
	public Long getCertificateRegistrationId();

	/**
	 * Sets the certificate registration ID of this asset manage req.
	 *
	 * @param certificateRegistrationId the certificate registration ID of this asset manage req
	 */
	public void setCertificateRegistrationId(Long certificateRegistrationId);

	/**
	 * Returns the contractid of this asset manage req.
	 *
	 * @return the contractid of this asset manage req
	 */
	public Long getContractid();

	/**
	 * Sets the contractid of this asset manage req.
	 *
	 * @param contractid the contractid of this asset manage req
	 */
	public void setContractid(Long contractid);

	/**
	 * Returns the partner ID of this asset manage req.
	 *
	 * @return the partner ID of this asset manage req
	 */
	public Long getPartnerId();

	/**
	 * Sets the partner ID of this asset manage req.
	 *
	 * @param partnerId the partner ID of this asset manage req
	 */
	public void setPartnerId(Long partnerId);

	/**
	 * Returns the status ca of this asset manage req.
	 *
	 * @return the status ca of this asset manage req
	 */
	public Long getStatusCa();

	/**
	 * Sets the status ca of this asset manage req.
	 *
	 * @param statusCa the status ca of this asset manage req
	 */
	public void setStatusCa(Long statusCa);

	/**
	 * Returns the comment ca of this asset manage req.
	 *
	 * @return the comment ca of this asset manage req
	 */
	@AutoEscape
	public String getCommentCa();

	/**
	 * Sets the comment ca of this asset manage req.
	 *
	 * @param commentCa the comment ca of this asset manage req
	 */
	public void setCommentCa(String commentCa);

	/**
	 * Returns the document ca ID of this asset manage req.
	 *
	 * @return the document ca ID of this asset manage req
	 */
	public Long getDocumentCaId();

	/**
	 * Sets the document ca ID of this asset manage req.
	 *
	 * @param documentCaId the document ca ID of this asset manage req
	 */
	public void setDocumentCaId(Long documentCaId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.viettel.ams.core.model.AssetManageReq assetManageReq);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.ams.core.model.AssetManageReq> toCacheModel();

	@Override
	public com.viettel.ams.core.model.AssetManageReq toEscapedModel();

	@Override
	public com.viettel.ams.core.model.AssetManageReq toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}