/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.viettel.ams.core.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MerEntity service. Represents a row in the &quot;Mer_Entity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.ams.core.model.impl.MerEntityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.ams.core.model.impl.MerEntityImpl}.
 * </p>
 *
 * @author MrNet
 * @see MerEntity
 * @see com.viettel.ams.core.model.impl.MerEntityImpl
 * @see com.viettel.ams.core.model.impl.MerEntityModelImpl
 * @generated
 */
public interface MerEntityModel extends BaseModel<MerEntity> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mer entity model instance should use the {@link MerEntity} interface instead.
	 */

	/**
	 * Returns the primary key of this mer entity.
	 *
	 * @return the primary key of this mer entity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mer entity.
	 *
	 * @param primaryKey the primary key of this mer entity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mer entity ID of this mer entity.
	 *
	 * @return the mer entity ID of this mer entity
	 */
	public long getMerEntityId();

	/**
	 * Sets the mer entity ID of this mer entity.
	 *
	 * @param merEntityId the mer entity ID of this mer entity
	 */
	public void setMerEntityId(long merEntityId);

	/**
	 * Returns the serial number of this mer entity.
	 *
	 * @return the serial number of this mer entity
	 */
	@AutoEscape
	public String getSerialNumber();

	/**
	 * Sets the serial number of this mer entity.
	 *
	 * @param serialNumber the serial number of this mer entity
	 */
	public void setSerialNumber(String serialNumber);

	/**
	 * Returns the unit price of this mer entity.
	 *
	 * @return the unit price of this mer entity
	 */
	public Double getUnitPrice();

	/**
	 * Sets the unit price of this mer entity.
	 *
	 * @param unitPrice the unit price of this mer entity
	 */
	public void setUnitPrice(Double unitPrice);

	/**
	 * Returns the mer ID of this mer entity.
	 *
	 * @return the mer ID of this mer entity
	 */
	public Long getMerId();

	/**
	 * Sets the mer ID of this mer entity.
	 *
	 * @param merId the mer ID of this mer entity
	 */
	public void setMerId(Long merId);

	/**
	 * Returns the contractid of this mer entity.
	 *
	 * @return the contractid of this mer entity
	 */
	public Long getContractid();

	/**
	 * Sets the contractid of this mer entity.
	 *
	 * @param contractid the contractid of this mer entity
	 */
	public void setContractid(Long contractid);

	/**
	 * Returns the group ID of this mer entity.
	 *
	 * @return the group ID of this mer entity
	 */
	public Long getGroupId();

	/**
	 * Sets the group ID of this mer entity.
	 *
	 * @param groupId the group ID of this mer entity
	 */
	public void setGroupId(Long groupId);

	/**
	 * Returns the warehouse ID of this mer entity.
	 *
	 * @return the warehouse ID of this mer entity
	 */
	public Long getWarehouseId();

	/**
	 * Sets the warehouse ID of this mer entity.
	 *
	 * @param warehouseId the warehouse ID of this mer entity
	 */
	public void setWarehouseId(Long warehouseId);

	/**
	 * Returns the construction ID of this mer entity.
	 *
	 * @return the construction ID of this mer entity
	 */
	public Long getConstructionId();

	/**
	 * Sets the construction ID of this mer entity.
	 *
	 * @param constructionId the construction ID of this mer entity
	 */
	public void setConstructionId(Long constructionId);

	/**
	 * Returns the is merchandise of this mer entity.
	 *
	 * @return the is merchandise of this mer entity
	 */
	public Long getIsMerchandise();

	/**
	 * Sets the is merchandise of this mer entity.
	 *
	 * @param isMerchandise the is merchandise of this mer entity
	 */
	public void setIsMerchandise(Long isMerchandise);

	/**
	 * Returns the status ID of this mer entity.
	 *
	 * @return the status ID of this mer entity
	 */
	public Long getStatusId();

	/**
	 * Sets the status ID of this mer entity.
	 *
	 * @param statusId the status ID of this mer entity
	 */
	public void setStatusId(Long statusId);

	/**
	 * Returns the parent ID of this mer entity.
	 *
	 * @return the parent ID of this mer entity
	 */
	public Long getParentId();

	/**
	 * Sets the parent ID of this mer entity.
	 *
	 * @param parentId the parent ID of this mer entity
	 */
	public void setParentId(Long parentId);

	/**
	 * Returns the user ID of this mer entity.
	 *
	 * @return the user ID of this mer entity
	 */
	public Long getUserId();

	/**
	 * Sets the user ID of this mer entity.
	 *
	 * @param userId the user ID of this mer entity
	 */
	public void setUserId(Long userId);

	/**
	 * Returns the upgrade parent ID of this mer entity.
	 *
	 * @return the upgrade parent ID of this mer entity
	 */
	public Long getUpgradeParentId();

	/**
	 * Sets the upgrade parent ID of this mer entity.
	 *
	 * @param upgradeParentId the upgrade parent ID of this mer entity
	 */
	public void setUpgradeParentId(Long upgradeParentId);

	/**
	 * Returns the part number of this mer entity.
	 *
	 * @return the part number of this mer entity
	 */
	@AutoEscape
	public String getPartNumber();

	/**
	 * Sets the part number of this mer entity.
	 *
	 * @param partNumber the part number of this mer entity
	 */
	public void setPartNumber(String partNumber);

	/**
	 * Returns the count of this mer entity.
	 *
	 * @return the count of this mer entity
	 */
	public Double getCount();

	/**
	 * Sets the count of this mer entity.
	 *
	 * @param count the count of this mer entity
	 */
	public void setCount(Double count);

	/**
	 * Returns the is temp of this mer entity.
	 *
	 * @return the is temp of this mer entity
	 */
	public Long getIsTemp();

	/**
	 * Sets the is temp of this mer entity.
	 *
	 * @param isTemp the is temp of this mer entity
	 */
	public void setIsTemp(Long isTemp);

	/**
	 * Returns the path of this mer entity.
	 *
	 * @return the path of this mer entity
	 */
	@AutoEscape
	public String getPath();

	/**
	 * Sets the path of this mer entity.
	 *
	 * @param path the path of this mer entity
	 */
	public void setPath(String path);

	/**
	 * Returns the original price of this mer entity.
	 *
	 * @return the original price of this mer entity
	 */
	public Double getOriginalPrice();

	/**
	 * Sets the original price of this mer entity.
	 *
	 * @param originalPrice the original price of this mer entity
	 */
	public void setOriginalPrice(Double originalPrice);

	/**
	 * Returns the manager name of this mer entity.
	 *
	 * @return the manager name of this mer entity
	 */
	@AutoEscape
	public String getManagerName();

	/**
	 * Sets the manager name of this mer entity.
	 *
	 * @param managerName the manager name of this mer entity
	 */
	public void setManagerName(String managerName);

	/**
	 * Returns the is expense of this mer entity.
	 *
	 * @return the is expense of this mer entity
	 */
	public Long getIsExpense();

	/**
	 * Sets the is expense of this mer entity.
	 *
	 * @param isExpense the is expense of this mer entity
	 */
	public void setIsExpense(Long isExpense);

	/**
	 * Returns the use group ID of this mer entity.
	 *
	 * @return the use group ID of this mer entity
	 */
	public Long getUseGroupId();

	/**
	 * Sets the use group ID of this mer entity.
	 *
	 * @param useGroupId the use group ID of this mer entity
	 */
	public void setUseGroupId(Long useGroupId);

	/**
	 * Returns the key search of this mer entity.
	 *
	 * @return the key search of this mer entity
	 */
	public Long getKeySearch();

	/**
	 * Sets the key search of this mer entity.
	 *
	 * @param keySearch the key search of this mer entity
	 */
	public void setKeySearch(Long keySearch);

	/**
	 * Returns the contract code of this mer entity.
	 *
	 * @return the contract code of this mer entity
	 */
	@AutoEscape
	public String getContractCode();

	/**
	 * Sets the contract code of this mer entity.
	 *
	 * @param contractCode the contract code of this mer entity
	 */
	public void setContractCode(String contractCode);

	/**
	 * Returns the description of this mer entity.
	 *
	 * @return the description of this mer entity
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this mer entity.
	 *
	 * @param description the description of this mer entity
	 */
	public void setDescription(String description);

	/**
	 * Returns the station ID of this mer entity.
	 *
	 * @return the station ID of this mer entity
	 */
	public Long getStationId();

	/**
	 * Sets the station ID of this mer entity.
	 *
	 * @param stationId the station ID of this mer entity
	 */
	public void setStationId(Long stationId);

	/**
	 * Returns the is inventory of this mer entity.
	 *
	 * @return the is inventory of this mer entity
	 */
	public Long getIsInventory();

	/**
	 * Sets the is inventory of this mer entity.
	 *
	 * @param isInventory the is inventory of this mer entity
	 */
	public void setIsInventory(Long isInventory);

	/**
	 * Returns the entity type of this mer entity.
	 *
	 * @return the entity type of this mer entity
	 */
	public Long getEntityType();

	/**
	 * Sets the entity type of this mer entity.
	 *
	 * @param entityType the entity type of this mer entity
	 */
	public void setEntityType(Long entityType);

	/**
	 * Returns the quality of this mer entity.
	 *
	 * @return the quality of this mer entity
	 */
	public Long getQuality();

	/**
	 * Sets the quality of this mer entity.
	 *
	 * @param quality the quality of this mer entity
	 */
	public void setQuality(Long quality);

	/**
	 * Returns the cat employee ID of this mer entity.
	 *
	 * @return the cat employee ID of this mer entity
	 */
	public Long getCatEmployeeId();

	/**
	 * Sets the cat employee ID of this mer entity.
	 *
	 * @param catEmployeeId the cat employee ID of this mer entity
	 */
	public void setCatEmployeeId(Long catEmployeeId);

	/**
	 * Returns the created date of this mer entity.
	 *
	 * @return the created date of this mer entity
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this mer entity.
	 *
	 * @param createdDate the created date of this mer entity
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the is lock of this mer entity.
	 *
	 * @return the is lock of this mer entity
	 */
	public Long getIsLock();

	/**
	 * Sets the is lock of this mer entity.
	 *
	 * @param isLock the is lock of this mer entity
	 */
	public void setIsLock(Long isLock);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.viettel.ams.core.model.MerEntity merEntity);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.ams.core.model.MerEntity> toCacheModel();

	@Override
	public com.viettel.ams.core.model.MerEntity toEscapedModel();

	@Override
	public com.viettel.ams.core.model.MerEntity toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}